### ISSUE TITLE
Problem compiled in Phonegap Build platform iOS

### ISSUE THREAD

**Issue by ReneCarmona** [chemerisuk/cordova-plugin-firebase-dynamiclinks#10]
Hi,

I haviing an issue using the plugin, i using phonegap build to compile project

In file included from /project/Shopnet/Plugins/cordova-plugin-firebase-dynamiclinks/AppDelegate+FirebaseDynamicLinks.m:2:
/project/Shopnet/Plugins/cordova-plugin-firebase-dynamiclinks/FirebaseDynamicLinks.h:4:9: fatal error: module 'Firebase' not found
@import Firebase;
 ~~~~~~~^~~~~~~~
1 error generated.

This is the log print in Phonegap Build, only have this problem in platform iOS, platform android works correctly

Any solution for this problem?

Thanks

**Comment by gsimonk** [comment]
Did you get any solution?

**Comment by ReneCarmona** [comment]
Hi,
I comment to you the possible soluction can be replace line **@import Firebase** by **#import <Firebase/Firebase.h** 

I create a pull request with this change 

I will appreciated if you can make this change

Thanks

**Comment by Stukongeluk** [comment]
The import thing doesn't work, you'll get an ```Expected "FILENAME" or <FILENAME>``` Error.

I'm just guessing but this piece of code hasn't been updated for 7 months.
The ```@import GoogleSignIn``` also is missing.
Does that mean we must install The firbase plugin and Sign in plugin before this plugin works with iOs?
And why does the android plugin not have the Google Signin or Firebase? 
I'm going to look around and see if all of this is actually needed

**Comment by chemerisuk** [comment]
Dup https://github.com/chemerisuk/cordova-plugin-firebase-dynamiclinks/pull/11

**Comment by bhavinwebdesk** [comment]
@Stukongeluk have you solved it?

**Comment by Stukongeluk** [comment]
@bhavinwebdesk Well I got an very old fork of this plugin which worked in my app. But I don't recommend it. I don't even know if the current version of this plugin fixed everything already.
