### ISSUE TITLE
Deprecated method used on iOS

### ISSUE THREAD

**Issue by jacobg** [chemerisuk/cordova-plugin-firebase-dynamiclinks#103]
When building iOS in Xcode, this warning is given:
```
'dynamicLinkFromUniversalLinkURL:' is deprecated: Use dynamicLinkFromUniversalLinkURL:completion: instead.
```

It goes on the following line of code:
https://github.com/chemerisuk/cordova-plugin-firebase-dynamiclinks/blob/91fc42cbc2337acd70c769221be38f41673424af/src/ios/AppDelegate%2BFirebaseDynamicLinksPlugin.m#L65

**Comment by marshall86** [comment]
I confirm the warning. Using Ionic 5 and Capacitor 2.4.5
