### ISSUE TITLE
onDynamicLink not firing on iOS 15.4

### ISSUE THREAD

**Issue by MarieGoudy** [chemerisuk/cordova-plugin-firebase-dynamiclinks#105]
I've implemented this library into my app and it all works great on Android and iOS up to 15.2. If I run the app on a physical tablet or an iPhone 8 simulator on iOS 15.2 it works, but running it on my physical iPhone 8 with iOS 15.4 doesn't work. I tried running the DynamicLinks diagnostic and got 

---- Firebase Dynamic Links diagnostic output start ----
Firebase Dynamic Links framework version 8.4.0
System information: OS iOS, OS version 15.4.1, model iPhone
Current date 2022-04-18 20:11:02 +0000
Device locale en-CA (raw en_CA), timezone America/Toronto
	Specified custom URL scheme is *** and Info.plist contains such scheme in CFBundleURLTypes key.
	AppID Prefix: ***, Team ID: ***, AppId Prefix equal to Team ID: YES
performDiagnostic completed successfully! No errors found.
---- Firebase Dynamic Links diagnostic output end ----

When I click on the dynamic link, the app opens, but the onDynamicLink function does not fire.
I'm using cordova-ios version 6.2.0.

Thank you!

**Comment by chemerisuk** [comment]
Duplicates https://github.com/chemerisuk/cordova-plugin-firebase-dynamiclinks/issues/15
