### ISSUE TITLE
when using with phonegap-plugin-push ios pod install fail

### ISSUE THREAD

**Issue by mohamedsharaf** [chemerisuk/cordova-plugin-firebase-dynamiclinks#11]
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "Firebase/Core":
  In Podfile:
    Firebase/Core (~> 5.0)

    Firebase/DynamicLinks (~> 5.0) was resolved to 5.0.0, which depends on
      Firebase/Core (= 5.0.0)

CocoaPods could not find compatible versions for pod "FirebaseAnalytics":
  In Podfile:
    Firebase/DynamicLinks (~> 5.0) was resolved to 5.0.0, which depends on
      Firebase/Core (= 5.0.0) was resolved to 5.0.0, which depends on
        FirebaseAnalytics (= 5.0.0)

    Firebase/DynamicLinks (~> 5.0) was resolved to 5.0.0, which depends on
      FirebaseDynamicLinks (= 3.0.0) was resolved to 3.0.0, which depends on
        FirebaseAnalytics (~> 5.0)

    FirebaseMessaging (~> 2.0.0) was resolved to 2.0.8, which depends on
      FirebaseAnalytics (~> 4.0)

**Comment by chemerisuk** [comment]
Current pushplugin version depends on firebase/core 4, but dynamic links plugin uses the latest firebase. You have to downgrade dynamic links plugin to version pre 1, and wait for the next major release of pushplugin

**Comment by mohamedsharaf** [comment]
for this who has same issue 

v0.14.0  also has same dependancy not working

        <framework src="Firebase/Core" type="podspec" spec="~> 5.0"/>
        <framework src="Firebase/DynamicLinks" type="podspec" spec="~> 5.0"/>

 only first version is working 
v0.13.2  …

**Comment by AndreasGassmann** [comment]
@mohamedsharaf There is a pull request open in the `phonegap-plugin-push` repo. I used that branch and it works flawlessly. They will merge it in the 3.0 release, but I don't know how long that will take...
