### ISSUE TITLE
cordova-plugin-firebase-dynamiclinks permission prompt issue in IOS

### ISSUE THREAD

**Issue by Dipeshjayswal** [chemerisuk/cordova-plugin-firebase-dynamiclinks#117]
I have used this plugin for social media dynamic links. 

My Ionic version is 6 and I'm using cordova-plugin-firebase-dynamiclinks plugin version ^7.0.2.

I want to remove the prompt shown in the screenshot or change the prompt message.

Please help me.

![MicrosoftTeams-image (55) (1)](https://user-images.githubusercontent.com/53213676/236130807-11d8d9db-85e7-49d6-8d5b-7a17ee27a3d0.jpeg)

**Comment by chemerisuk** [comment]
I don’t think your issue is related to this plugin. This is a system dialog.
