### ISSUE TITLE
Using with cordova-plugin-fcm ?

### ISSUE THREAD

**Issue by feruzm** [chemerisuk/cordova-plugin-firebase-dynamiclinks#14]
How to get around of the error message?

```*** Terminating app due to uncaught exception 'com.firebase.core', reason: 'Default app has already been configured.'```

App crashes on iOS due to above error...

I assume it is because I am also using firebase cloud messaging plugin. Any work around?

**Edit:** commenting out in fcm plugin source code helped but I wish there was built-in workaround
```
    // [START configure_firebase]
    //[FIRApp configure];
    // [END configure_firebase]
```

**Comment by chemerisuk** [comment]
The problem is in their code, not mine.
