### ISSUE TITLE
How to test the plugin

### ISSUE THREAD

**Issue by AndreasGassmann** [chemerisuk/cordova-plugin-firebase-dynamiclinks#14]
Hi,

I'm a little bit confused about how I can test if this plugin works. (I'm testing on iOS)

I have the `ionic-plugin-deeplinks` plugin installed and used it to handle deeplinks. Now I also added this plugin.

When I open a dynamic link, I can see that the `ionic-plugin-deeplinks` callback is called with a dynamic link, but the callback of this plugin is never called. I wonder if this is due to an incompatibility of those 2 plugins, or if it's something else.

Also, if on the firebase console I select "If app not installed > Open in App Store", it seems to ALWAYS open the app store, regardless if the live version from the store, or the new test version with dynamiclinks is installed. Can I only test this if my app (the one that includes the dynamic link plugin) is live on production?

Last question, what **should** the value for the Associated Domains be?
After compiling the plugin, it looked like this:
```applinks:subdomain.mydomain.com```

But I read on stackoverflow somewhere that it should be the page link url:
```applinks:myname.page.link```

Which one is needed?

Thanks for your help

**Comment by murshid1988** [comment]
When I installed the plugin I got both `applinks:`My subdomain and the page.link.

**Comment by jullicer** [comment]
@murshid1988 how did you add both ? comma separated or 1 item per link ?

**Comment by murshid1988** [comment]
@jullicer the installation code itself has both options with the switch `--variable`

`cordova plugin add cordova-plugin-firebase-dynamiclinks --save --variable APP_DOMAIN="example.com" --variable PAGE_LINK_DOMAIN="example.page.link"`

Or else if you want to change something, you can do in `config.xml`

Search for a similar code like below add the necessary ones

```
<plugin name="cordova-plugin-firebase-dynamiclinks" spec="^1.0.0">
        <variable name="APP_DOMAIN" value="example.com" />
        <variable name="APP_PATH" value="/" />
        <variable name="PAGE_LINK_DOMAIN" value="example.page.link" />
        <variable name="FIREBASE_DYNAMIC_LINKS_VERSION" value="16.0.+" />
</plugin>
```

**Comment by rajashekaranugu** [comment]
> Hi,
> 
> I'm a little bit confused about how I can test if this plugin works. (I'm testing on iOS)
> 
> I have the `ionic-plugin-deeplinks` plugin installed and used it to handle deeplinks. Now I also added this plugin.
> 
> When I open a dynamic link, I can see that the `ionic-plugin-deeplinks` callback is called with a dynamic link, but the callback of this plugin is never called. I wonder if this is due to an incompatibility of those 2 plugins, or if it's something else.
> 
> Also, if on the firebase console I select "If app not installed > Open in App Store", it seems to ALWAYS open the app store, regardless if the live version from the store, or the new test version with dynamiclinks is installed. Can I only test this if my app (the one that includes the dynamic link plugin) is live on production?
> 
> Last question, what **should** the value for the Associated Domains be?
> After compiling the plugin, it looked like this:
> `applinks:subdomain.mydomain.com`
> 
> But I read on stackoverflow somewhere that it should be the page link url:
> `applinks:myname.page.link`
> 
> Which one is needed?
> 
> Thanks for your help

Hi @murshid1988, can you please let us know how did you integrate both and how your dynamic links and deep links looked like??

I have my dynamic links like https://abc.page.link/loginPage/?xyz=true
and my deeplink is like myapp://mysite.com
