### ISSUE TITLE
iOS WebContent: 113 issue

### ISSUE THREAD

**Issue by feruzm** [chemerisuk/cordova-plugin-firebase-dynamiclinks#16]
I get this error on xcode when calling sendInvitation on iOS (10.3.2), no other reactions...

```Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service```

Any idea how to fix that? I think it might be wkwebview related?!

**Comment by chemerisuk** [comment]
Is it a blocker or just a warning?

**Comment by feruzm** [comment]
It blocks, nothing happens... only after 1 or 2 seconds I see 
```
2017-06-28 13:55:40.019655+0300 projectX[9213:5733665] Could not signal service com.apple.WebKit.Networking: 113: Could not find specified service
```

**Comment by feruzm** [comment]
Not sure what fixed it, but it looks like after reinstall of plugin to latest version (0.10.0) seem to fix it, working ok now... Somewhat strange behavior for iOS users to require Google account though, Android is ok since everyone has google account there...

Would really like it to be more general one without requiring user to login to their gmail account, anyone has workaround or alternative methods?!

**Comment by chemerisuk** [comment]
@feruzm true, FDL require Google signin on iOS. This is how they work (read official docs)

**Comment by feruzm** [comment]
@chemerisuk yeah, I know... when I tried on real device and few uses cases, it is somewhat inconvenient for users though 😐
