### ISSUE TITLE
Found com.google.android.gms:play-services-auth:+, but version 11.0.+ is needed for the google-services plugin.

### ISSUE THREAD

**Issue by saiy2k** [chemerisuk/cordova-plugin-firebase-dynamiclinks#17]
I am getting following error when trying to build the android project

        :prepareMeLeolinShortcutBadger1111Library
        :prepareOrgApacheCordovaCordovaLib623DebugLibrary
        :prepareDebugDependencies
        :compileDebugAidl
        :compileDebugRenderscript
        :generateDebugBuildConfig
        :generateDebugResValues
        :processDebugGoogleServices
        Found com.google.android.gms:play-services-auth:+, but version 11.0.+ is needed for the google-services plugin.
        Found com.google.android.gms:play-services-identity:+, but version 11.0.+ is needed for the google-services
        plugin.
        :processDebugGoogleServices FAILED
        
        FAILURE: Build failed with an exception.
        
        * What went wrong:
        Execution failed for task ':processDebugGoogleServices'.
        > Please fix the version conflict either by updating the version of the google-services plugin (information
        about the latest version is available at
        https://bintray.com/android/android-tools/com.google.gms.google-services/) or updating the version of
        com.google.android.gms to 11.0.+.
        
        * Try:
        Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
        
        BUILD FAILED
        
        Total time: 3.084 secs
        Error: /home/saiy2k/projects/ionic/gr/platforms/android/gradlew: Command failed with exit code 1 Error output:
        Note: Some input files use or override a deprecated API.
        Note: Recompile with -Xlint:deprecation for details.
        Note: Some input files use or override a deprecated API.
        Note: Recompile with -Xlint:deprecation for details.
        
        FAILURE: Build failed with an exception.
        
        * What went wrong:
        Execution failed for task ':processDebugGoogleServices'.
        > Please fix the version conflict either by updating the version of the google-services plugin (information
        about the latest version is available at
        https://bintray.com/android/android-tools/com.google.gms.google-services/) or updating the version of
        com.google.android.gms to 11.0.+.

**My Ionic Info:**
Global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.12
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : android 6.2.3
    Ionic Framework                 : ionic-angular 3.4.2

System:

    Node       : v6.11.0
    OS         : Linux 4.10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 5.0.4 

**Cordova Plugin List**
cordova-plugin-app-event 1.2.0 "Application Events"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-background-mode 0.7.2 "BackgroundMode"
cordova-plugin-badge 0.7.4 "Badges"
cordova-plugin-console 1.0.5 "Console"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-facebook4 1.7.4 "Facebook Connect"
cordova-plugin-firebase-analytics 0.10.1 "FirebaseAnalyticsPlugin"
cordova-plugin-firebase-dynamiclinks 0.10.0 "FirebaseDynamicLinksPlugin"
cordova-plugin-googleplus 5.1.1 "Google SignIn"
cordova-plugin-inappbrowser 1.7.1 "InAppBrowser"
cordova-plugin-network-information 1.3.3 "Network Information"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.2 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
cordova-plugin-x-socialsharing 5.1.8 "SocialSharing"
de.appplant.cordova.plugin.local-notification 0.8.5 "LocalNotification"
es6-promise-plugin 4.1.0 "Promise"
ionic-plugin-keyboard 2.2.1 "Keyboard"

I tried doing some fix by following the solutions for similar issue @ 
https://github.com/EddyVerbruggen/nativescript-plugin-firebase/issues/163 and
https://github.com/NativeScript/push-plugin/issues/97

But couldn't get it working. Any official fix would be great.

**Comment by chemerisuk** [comment]
https://github.com/chemerisuk/cordova-plugin-firebase-analytics#faq

**Comment by saiy2k** [comment]
oh. Didn't notice the FAQ. Thanks :+1:
