### ISSUE TITLE
error: cannot access zzbgl class file for com.google.android.gms.internal.zzbgl not found

### ISSUE THREAD

**Issue by Balticstar1** [chemerisuk/cordova-plugin-firebase-dynamiclinks#17]
<Here is my build.gradle>
apply plugin: 'com.android.application'

android {
    compileSdkVersion 28
    defaultConfig {
        applicationId "com.layton.govirul"
        minSdkVersion 19
        targetSdkVersion 28
        multiDexEnabled true
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:28.0.0-alpha1 (*)'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    implementation 'com.google.android.gms:play-services-maps:15.0.1'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    implementation 'com.android.support:design:28.0.0-alpha1'
    implementation 'com.firebase:geofire-android:2.1.1'
    implementation 'com.google.android.gms:play-services:12.0.1'
    implementation 'com.google.android.gms:play-services-maps:12.0.1'

    implementation 'com.github.glomadrian:MaterialAnimatedSwitch:1.1@aar'
    implementation 'com.firebase:geofire-android:2.1.2'
    implementation 'com.google.firebase:firebase-core:16.0.1'
    implementation 'com.google.firebase:firebase-database:16.0.1'
    implementation 'com.google.firebase:firebase-auth:16.0.3'
    implementation 'com.google.firebase:firebase-storage:16.0.2'

    implementation 'com.android.support:multidex:1.0.3'
    implementation 'uk.co.chrisjenx:calligraphy:2.3.0'
    implementation 'com.rengwuxian.materialedittext:library:2.1.4'
    implementation 'com.paypal.sdk:paypal-android-sdk:2.15.3'
    implementation 'com.github.d-max:spots-dialog:1.1@aar'
    implementation 'com.github.bumptech.glide:glide:4.0.0'
    implementation 'com.android.support:design:28.0.0-alpha1(*)'
    implementation 'com.android.support:cardview-v7:28.0.0-alpha1(*)'
    implementation 'com.github.jd-alexander:library:1.1.0'
    implementation 'com.android.support:design-snackbar:28.0.0-alpha1'
}
apply plugin: 'com.google.gms.google-services'

**Comment by Balticstar1** [comment]
Please help, I have been stuck on this error for 2 days now

**Comment by jullicer** [comment]
try setting play-services to +

**Comment by oguzhangedik** [comment]
I got that error when i try to add google map in my project and :

In my case, i have changed :

implementation 'com.google.android.gms:play-services:12.0.1'
with

implementation 'com.google.android.gms:play-services-maps:17.0.0'
and it have resolved.

**Comment by bulent017** [comment]
> Please help, I have been stuck on this error for 2 days now

I'm on day 3
