### ISSUE TITLE
Plugin installation ends with error on android

### ISSUE THREAD

**Issue by solonik1** [chemerisuk/cordova-plugin-firebase-dynamiclinks#19]
Hi @chemerisuk, cannot add this plugin on android, because an exception:
Error: cmd: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred evaluating root project 'android'.
> Failed to apply plugin [class 'com.google.gms.googleservices.GoogleServicesPlugin']
   > For input string: "+"
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

Can you help? Thx

**Comment by chemerisuk** [comment]
https://github.com/chemerisuk/cordova-plugin-firebase-analytics#faq

**Comment by gianpaj** [comment]
I have the same issue and I couldn't fix this by changing the `project.properties` file.

@solonik1 did you solve this?

On top of the file it says:
```
# This file is automatically generated by Android Tools.
# Do not modify this file -- YOUR CHANGES WILL BE ERASED!
```

Some info:
```
$ ionic info

cli packages: (./node_modules)

    @ionic/cli-plugin-cordova       : 1.6.2
    @ionic/cli-plugin-ionic-angular : 1.4.1
    @ionic/cli-utils                : 1.7.0
    ionic (Ionic CLI)               : 3.7.0

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 26.0.2
    Node              : v6.10.2
    OS                : macOS Sierra
    Xcode             : Xcode 8.3.3 Build version 8E3004b
    ios-deploy        : 1.9.1
    ios-sim           : 5.0.8
    npm               : 4.6.1
```

**Comment by solonik1** [comment]
Hi, i could solve my problem with this modified project.properties file

# This file is automatically generated by Android Tools.
# Do not modify this file -- YOUR CHANGES WILL BE ERASED!
#
# This file must be checked in Version Control Systems.
#
# To customize properties used by the Ant build system edit
# "ant.properties", and override values to adapt the script to your
# project structure.
#
# To enable ProGuard to shrink and obfuscate your code, uncomment this (available properties: sdk.dir, user.home):
#proguard.config=${sdk.dir}/tools/proguard/proguard-android.txt:proguard-project.txt
# Project target.
target=android-25
android.library.reference.1=CordovaLib
cordova.system.library.1=com.google.android.gms:play-services-ads:11.0.+
cordova.system.library.2=com.android.support:support-v4:24.1.1+
cordova.system.library.3=com.facebook.android:facebook-android-sdk:4.+
cordova.system.library.4=com.google.firebase:firebase-core:11.0.+
#cordova.gradle.include.1=cordova-plugin-firebase-analytics/#######-build.gradle
cordova.system.library.5=com.google.firebase:firebase-invites:11.0.+
cordova.system.library.6=com.google.firebase:firebase-dynamic-links:11.0.+
cordova.system.library.7=com.google.android.gms:play-services-auth:11.0.+
cordova.system.library.8=com.google.android.gms:play-services-identity:11.0.+
cordova.system.library.9=com.android.support:support-v4:24.1.1+
cordova.gradle.include.2=phonegap-plugin-push/#######-push.gradle
cordova.system.library.10=com.android.support:support-v13:23+
cordova.system.library.11=com.google.android.gms:play-services-gcm:11.0.+
cordova.system.library.12=me.leolin:ShortcutBadger:1.1.14@aar

Hope, this help you

**Comment by gianpaj** [comment]
Nothing same issue:
```
Error: app/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugGoogleServices'.
> Please fix the version conflict either by updating the version of the google-services plugin (information about the latest version is available at https://bintray.com/android/android-tools/com.google.gms.google-services/) or updating the version of com.google.android.gms to 11.0.+.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

This is the original file.
```
target=android-25
android.library.reference.1=CordovaLib
cordova.system.library.1=com.google.android.gms:play-services-auth:+
cordova.system.library.2=com.google.android.gms:play-services-identity:+
cordova.system.library.3=com.android.support:support-v13:23+
cordova.gradle.include.1=phonegap-plugin-push/project-push.gradle
cordova.gradle.include.2=phonegap-plugin-push/app-push.gradle
cordova.system.library.4=com.google.android.gms:play-services-gcm:11+
cordova.system.library.5=me.leolin:ShortcutBadger:1.1.14@aar
cordova.system.library.6=com.facebook.android:facebook-android-sdk:4.+
cordova.system.library.7=com.android.support:support-v4:24.1.1+
cordova.system.library.8=com.soundcloud.android:android-crop:1.0.0@aar
cordova.system.library.9=com.mixpanel.android:mixpanel-android:5.1.4
cordova.system.library.10=com.google.android.gms:play-services-base:+
cordova.system.library.11=com.google.android.gms:play-services-gcm:+
cordova.system.library.12=com.android.support:support-v4:24.1.1+
cordova.system.library.13=com.google.firebase:firebase-core:11.0.+
cordova.gradle.include.3=cordova-plugin-firebase-analytics/app-build.gradle
cordova.system.library.14=com.google.firebase:firebase-invites:11.0.+
cordova.system.library.15=com.google.firebase:firebase-dynamic-links:11.0.+
```

This is what I tried:
```diff
---
+++
@@ -1,18 +1,18 @@
 target=android-25
 android.library.reference.1=CordovaLib
-cordova.system.library.1=com.google.android.gms:play-services-auth:11.0.+
-cordova.system.library.2=com.google.android.gms:play-services-identity:11.0.+
+cordova.system.library.1=com.google.android.gms:play-services-auth:+
+cordova.system.library.2=com.google.android.gms:play-services-identity:+
 cordova.system.library.3=com.android.support:support-v13:23+
 cordova.gradle.include.1=phonegap-plugin-push/project-push.gradle
 cordova.gradle.include.2=phonegap-plugin-push/app-push.gradle
 cordova.system.library.4=com.google.android.gms:play-services-gcm:11+
 cordova.system.library.5=me.leolin:ShortcutBadger:1.1.14@aar
 cordova.system.library.6=com.facebook.android:facebook-android-sdk:4.+
 cordova.system.library.7=com.android.support:support-v4:24.1.1+
 cordova.system.library.8=com.soundcloud.android:android-crop:1.0.0@aar
 cordova.system.library.9=com.mixpanel.android:mixpanel-android:5.1.4
 cordova.system.library.10=com.google.android.gms:play-services-base:+
-cordova.system.library.11=com.google.android.gms:play-services-gcm:11+
+cordova.system.library.11=com.google.android.gms:play-services-gcm:+
 cordova.system.library.12=com.android.support:support-v4:24.1.1+
 cordova.system.library.13=com.google.firebase:firebase-core:11.0.+
 cordova.gradle.include.3=cordova-plugin-firebase-analytics/app-build.gradle
```

**Comment by solonik1** [comment]
try this:
1) cordova platform rm android, remove all plugins/modules in cordova directory
2) cordova platform add android
3) replace + with 11.0.+ (see my example)
4) update all google services under: Android Studio->Tools->Android->SDK Manager->SDK Tools (see image). Be careful: dont update Android Studio to version 2.3.3, is unstable version. I use version 2.3.1
5) cordova build android
https://user-images.githubusercontent.com/25851262/29064226-a1218f52-7c28-11e7-8e6d-ef17e26ff0c8.PNG
