### ISSUE TITLE
Phonegap Build iOS - Error: pod: Command failed with exit code 1

### ISSUE THREAD

**Issue by joelfunk** [chemerisuk/cordova-plugin-firebase-dynamiclinks#19]
Everything works with Android, but I cannot get it build on Phongap Build service on iOS:

Failed to install 'cordova-plugin-firebase-dynamiclinks': Error: pod: Command failed with exit code 1
    at ChildProcess.whenDone (/private/project/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Socket.stream.socket.on (internal/child_process.js:380:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:599:12)
pod: Command failed with exit code 1

Here is the main part of my config.xml:

	<preference name="phonegap-version" value="cli-8.0.0" />
	<preference name="DisallowOverscroll" value="true" />
	<preference name="android-targetSdkVersion" value="26" />
	<preference name="android-minSdkVersion" value="16" />

	<preference name="orientation" value="portrait" />
	<preference name="DisallowOverscroll" value="true"/>
	<preference name="StatusBarOverlaysWebView" value="false" />
	<preference name="StatusBarBackgroundColor" value="#333333" />

	<plugin name="cordova-plugin-camera" source="npm" spec="~2.4.1" />
	<plugin name="cordova-plugin-device" source="npm" spec="~1.1.6" />
	<plugin name="cordova-plugin-dialogs" source="npm" spec="~1.3.3" />
	<plugin name="cordova-plugin-geolocation" source="npm" spec="~2.4.3" />
	<plugin name="cordova-plugin-inappbrowser" source="npm" spec="~3.0.0" />
	<plugin name="cordova-plugin-network-information" source="npm" spec="~1.3.3" />
	<plugin name="cordova-plugin-statusbar" source="npm" spec="~2.1.2"/>
	<plugin name="cordova-plugin-splashscreen" source="npm" spec="~5.0.2"/>
	<plugin name="cordova-plugin-whitelist" source="npm" spec="~1.3.3"/>
	<plugin name="phonegap-plugin-push" spec="~2.1.2">
		<variable name="FCM_VERSION" value="11.0.+" />
	</plugin>
	<plugin name="cordova-plugin-x-socialsharing" source="npm" />
	<plugin name="cordova-plugin-firebase-dynamiclinks" source="npm" spec="1.0.1">
		<param name="APP_DOMAIN" value="http://www.unitedhive.com" />
		<param name="PAGE_LINK_DOMAIN" value="unitedhive.page.link" />
		<param name="FIREBASE_DYNAMIC_LINKS_VERSION" value="11.0.+" />
	</plugin>

**Comment by chemerisuk** [comment]
Duplicates 
https://github.com/chemerisuk/cordova-plugin-firebase-dynamiclinks/issues/11

**Comment by joelfunk** [comment]
Downgrading the Dynamic Links plugin version to v0.14.0 or v0.13.2 did not work for me.  Is there another plugin that needs to be changed as well?
