### ISSUE TITLE
First open works, second open crashes...

### ISSUE THREAD

**Issue by adamgins** [chemerisuk/cordova-plugin-firebase-dynamiclinks#2]
Hi, i am getting the following crash when I open a dynamic link from the browser...
![screen shot 2018-05-03 at 10 20 12 pm](https://user-images.githubusercontent.com/7233741/39576147-80bdd088-4f20-11e8-8b9b-3c30932c5272.png)
Any ideas please?

**Comment by vishal-iosdeveloper** [comment]
For me,
I am not getting any event by this plugin.
I have a live app on AppStore. I am providing "dynamic link" feature in Update.
But this plugin isn't providing me event.
For Test FireBase dynamic link,
I did go throught below steps :
https://stackoverflow.com/questions/40470679/testing-firebase-deep-linking-for-install-path

**Comment by yashdabi** [comment]
"cordova-plugin-firebase-dynamiclinks": "^4.0.2",
Working for me
