### ISSUE TITLE
invites sent, however email did not arrived

### ISSUE THREAD

**Issue by solonik1** [chemerisuk/cordova-plugin-firebase-dynamiclinks#20]
There is already a bug, however still openly. Is there a solution  for it? (https://github.com/Telerik-Verified-Plugins/Firebase-Invites/issues/3)
@chemerisuk Thx

**Comment by chemerisuk** [comment]
I don't have such an issue

**Comment by solonik1** [comment]
Sorry, incorrect settings on firebase. Thank you for your help.

**Comment by aroraenterprise** [comment]
@solonik1 Could I ask what your incorrect settings were as I am having a similar issue. I have the sha1 set in firebase and SMS are working however, emails from the plugin are not being sent out. Your advice would be really appreciated!

**Comment by solonik1** [comment]
Hello @aroraenterprise, I dont know this any more. You could try to set SHA-256 too. I have both SHA1 and SHA256. Sorry.
https://www.youtube.com/watch?v=sFPo296OQqk&t=388s, 6:30 min
