### ISSUE TITLE
'GoogleUtilities/GULAppEnvironmentUtil.h' file not found

### ISSUE THREAD

**Issue by Gemeapp** [chemerisuk/cordova-plugin-firebase-dynamiclinks#22]
I am having some trouble building my app after adding this plugin to my solution, so now I started from scratch

First I created a blank ionic project

ionic start firebasetest blank

after building this everything was ok

then I added this plugin and the Ionic wrapper
ionic cordova plugin add cordova-plugin-firebase-dynamiclinks --save --variable APP_DOMAIN="test.com" --variable PAGE_LINK_DOMAIN="mytest.page.link"

and

npm install --save @ionic-native/firebase-dynamic-links

and are now getting the missing file error
/Users/thorvald/firebasetest/platforms/ios/Pods/FirebaseCore/Firebase/Core/FIRLogger.m:18:9: fatal error: 'GoogleUtilities/GULAppEnvironmentUtil.h' file not found
#import <GoogleUtilities/GULAppEnvironmentUtil.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

My configuration:
Ionic:

   ionic (Ionic CLI)  : 4.3.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.0, (and 5 other plugins)

System:

   ios-deploy : 2.0.0
   ios-sim    : 5.0.13
   NodeJS     : v6.11.1 (/usr/local/lib/node_modules/node/lib/node_modules/node/bin/node)
   npm        : 6.4.1
   OS         : macOS Sierra
   Xcode      : Xcode 9.1 Build version 9B55

my pod file contains

# DO NOT MODIFY -- auto-generated by Apache Cordova
platform :ios, '8.0'
target 'MyApp' do
	project 'MyApp.xcodeproj'
	pod 'Firebase/Core', '~> 5.0'
	pod 'Firebase/DynamicLinks', '~> 5.0'
end

What am I missing?

**Comment by ThorvaldAagaard** [comment]
This is a compiler problem. Basically I just deleted 3 lines with xcconfig in the file platforms\ios\cordova\lib\build.js - the problem is know at cordova and might be solved i a future version of the cordova-ios platform

**Comment by dunice-boldirev** [comment]
Hello @ThorvaldAagaard ! 

I have changed `platforms\ios\cordova\lib\build.js` as as suggested [here](https://github.com/apache/cordova-ios/pull/398).
After change build.js arise new problem with iPhone.
When application open via dynamic link on iPhone application crashed. 
Please see gif image


![ezgif-6-e90a996d01c3](https://user-images.githubusercontent.com/11989481/48420776-2f3fe180-e76c-11e8-9272-fb157cec1c5a.gif)

In Xcode I get error

![2018-11-14 21 25 08](https://user-images.githubusercontent.com/11989481/48503690-d51a4b80-e853-11e8-852f-008a2a65fb5f.png)


Let me know if you have encountered such a problem and know how to solve it.

**Ionic info**

       Ionic:

          ionic (Ionic CLI)  : 4.3.1 (/Users/dunice/.nvm/versions/node/v9.11.2/lib/node_modules/ionic)
          Ionic Framework    : ionic-angular 3.9.2
          @ionic/app-scripts : not installed

       Cordova:

          cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
          Cordova Platforms     : ios 4.5.5
          Cordova Plugins       : cordova-plugin-ionic-webview 2.2.3, (and 7 other plugins)

       System:

          Android SDK Tools : 26.1.1 (/Users/dunice/Library/Android/sdk)
          NodeJS            : v9.11.2 (/Users/dunice/.nvm/versions/node/v9.11.2/bin/node)
          npm               : 5.6.0
          OS                : macOS High Sierra
          Xcode             : Xcode 10.0 Build version 10A255

Let me know if you need more information from me.

**Comment by ThorvaldAagaard** [comment]
Sorry, still not that far, as I am focusing on Android, and did just check, that the IOS version would start (and navigate thru AppStore if needed). I am not listening on the events yet

**Comment by dunice-boldirev** [comment]
Unfortunately, I got this problem without listening of events

**Comment by ankit18singh** [comment]
Facing similar issue.

**Comment by jrezalla** [comment]
@dunice-boldirev I was having the same issue.

I fix the problem by changing the build.js has you did, and changing the file AppDelegate+FirebaseDynamicLinksPlugin.m inside the folder Plugins/cordova-plugin-firebase-dynamiclinks

```
// Borrowed from http://nshipster.com/method-swizzling/
+ (void)load {
    [FIRApp configure];
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
```

You just need to add **[FIRApp configure];** and everything should work.
