### ISSUE TITLE
Application crashes after open via dynamic link on IPhone

### ISSUE THREAD

**Issue by dunice-boldirev** [chemerisuk/cordova-plugin-firebase-dynamiclinks#23]
Hello! 
When I open application via dynamic link on iPhone I have crashed application. 
Please see gif image

![ezgif-6-e90a996d01c3](https://user-images.githubusercontent.com/11989481/48420776-2f3fe180-e76c-11e8-9272-fb157cec1c5a.gif)

In the same time dynamic links work well on Android. 
In process of build app I not get any errors!

**Ionic info**

       Ionic:

          ionic (Ionic CLI)  : 4.3.1 (/Users/dunice/.nvm/versions/node/v9.11.2/lib/node_modules/ionic)
          Ionic Framework    : ionic-angular 3.9.2
          @ionic/app-scripts : not installed

       Cordova:

          cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
          Cordova Platforms     : ios 4.5.5
          Cordova Plugins       : cordova-plugin-ionic-webview 2.2.3, (and 7 other plugins)

       System:

          Android SDK Tools : 26.1.1 (/Users/dunice/Library/Android/sdk)
          NodeJS            : v9.11.2 (/Users/dunice/.nvm/versions/node/v9.11.2/bin/node)
          npm               : 5.6.0
          OS                : macOS High Sierra
          Xcode             : Xcode 10.0 Build version 10A255

 **Firebase dynamic links version**

       "cordova-plugin-firebase-dynamiclinks": {
               "FIREBASE_DYNAMIC_LINKS_VERSION": "16.1.+",
                ...
       }

Could you say me what could be the reason for this strange behavior?
Let me know if you need more information from me.

**Comment by dunice-boldirev** [comment]
Moved to [issue#22](https://github.com/chemerisuk/cordova-plugin-firebase-dynamiclinks/issues/22)

**Comment by ankit18singh** [comment]
Same issue. @dunice-boldirev did you found any solution?

**Comment by dunice-boldirev** [comment]
@ankit18singh  Unfortunately not. I had to abandon firebase. I now use https://branch.io/
