### ISSUE TITLE
firebase-core missing for Android?

### ISSUE THREAD

**Issue by jacobg** [chemerisuk/cordova-plugin-firebase-dynamiclinks#26]
This plugin installs `Firebase/Core` on iOS, but there is not declaration to install firebase-core on Android like this:
`<framework src="com.google.firebase:firebase-core:16.0.6" />`

Indeed, unless I add that declaration to my own plugin, then this build error occurs:
`The app gradle file must have a dependency on com.google.firebase:firebase-core for Firebase services to work as intended.`

Should that be added to this plugin?

**Comment by chemerisuk** [comment]
As far as I understood from the [docs](https://firebase.google.com/docs/dynamic-links/android/receive) for dynamic links `firebase-core` dependency is not required.

**Comment by jacobg** [comment]
In the link you sent the part where it seems like it requires firebase-core is the vague instruction:
`If you haven't yet connected your app to your Firebase project, do so from the Firebase console.`

The linked page says the Firebase SDK is required like in attached screenshot below.

That verification process where you run the app the first time with firebase-core and google-services.json is how it lets you pick which app to create a dynamic link for. I think that's also how they will add your app to their https://{your_domain}.page.link/.well-known/assetlinks.json file, although Firebase hasn't seemed to do that for me, and I need to investigate that.

When I was doing this yesterday, I think I also remember getting a Java compilation error without the SDK.

Am I misunderstanding something?

As a side point, I'm probably going to open another issue for iOS, because of some Xcode linking errors, after I complete my investigation of that.

<img width="758" alt="screen shot 2019-02-02 at 7 00 41 pm" src="https://user-images.githubusercontent.com/736985/52170689-e705df00-271c-11e9-9b4c-908de1c2c577.png">

**Comment by jacobg** [comment]
Also the following exception occurs, which indicates the need for the Firebase SDK:

```
by.chemerisuk.cordova.firebase.FirebaseDynamicLinksPlugin.respondWithDynamicLink
FirebaseDynamicLinksPlugin.java, line 41
java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.fareclock.tc. Make sure to call FirebaseApp.initializeApp(Context) first.

com.google.firebase.FirebaseApp.getInstance com.google.firebase:firebase-common@@16.0.2:240
com.google.firebase.dynamiclinks.FirebaseDynamicLinks.getInstance
by.chemerisuk.cordova.firebase.FirebaseDynamicLinksPlugin.respondWithDynamicLink FirebaseDynamicLinksPlugin.java:41
by.chemerisuk.cordova.firebase.FirebaseDynamicLinksPlugin.onNewIntent FirebaseDynamicLinksPlugin.java:29
org.apache.cordova.PluginManager.onNewIntent PluginManager.java:327
```
