### ISSUE TITLE
cordova-plugin-firebase-dynamiclinks : export declare type ObservedValueOf<O> = O extends ObservableInput<infer T> ? T : never;

### ISSUE THREAD

**Issue by sawanmhjn** [chemerisuk/cordova-plugin-firebase-dynamiclinks#29]
Having issue in setuping firebase dynamic link in my ionic project. 

Steps are described which I follow for setup this plugin : 
1) Install the plugin using 
`ionic cordova plugin add cordova-plugin-firebase-dynamiclinks --save --variable APP_DOMAIN="example.com" --variable PAGE_LINK_DOMAIN="example.page.link"`
2) Install the NPM package for this using 
`npm install @ionic-native/firebase-dynamic-links`
3) Added below code to my app.component.ts file 
```
import { FirebaseDynamicLinks } from '@ionic-native/firebase-dynamic-links/ngx';


constructor(private firebaseDynamicLinks: FirebaseDynamicLinks) { }

...
// Handle the logic here after opening the app with the Dynamic link
this.firebaseDynamicLinks.onDynamicLink()
  .subscribe((res: any) => console.log(res), (error:any) => console.log(error));


```
After that I tried to build my project and suddenly got an error : 

```
vendor.js:2135 ERROR Error: Uncaught (in promise): TypeError: Object(...) is not a function
TypeError: Object(...) is not a function
    at FirebaseDynamicLinks.onDynamicLink (vendor.js:93256)
    at main.js:1006
    at t.invoke (polyfills.js:3)
    at Object.onInvoke (vendor.js:5446)
    at t.invoke (polyfills.js:3)
    at r.run (polyfills.js:3)
    at polyfills.js:3
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (vendor.js:5437)
    at t.invokeTask (polyfills.js:3)
    at c (polyfills.js:3)
    at polyfills.js:3
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (vendor.js:5437)
    at t.invokeTask (polyfills.js:3)
    at r.runTask (polyfills.js:3)
    at o (polyfills.js:3)
defaultErrorLogger @ vendor.js:2135
```
3) For remove this error, I googled some blogs and got a link through remove this using 
` npm i rxjs@^6.0 rxjs-compat`

After that I build my project again, Now i got some strange error : 

> [16:34:53]  typescript: node_modules/rxjs/internal/types.d.ts, line: 81 
>             'ObservableInput' only refers to a type, but is being used as a value here. 
> 
>       L81:  export declare type ObservedValueOf<O> = O extends ObservableInput<infer T> ? T : never;

I googled but can't solve this. 

I tried to remove node_modules and install again and doing same for platform but it persist yet. 

Here is my environment info : 

> ✔ Gathering environment info - done!
> 
> Ionic:
> 
>    ionic (Ionic CLI)  : 4.1.2 (/usr/local/lib/node_modules/ionic)
>    Ionic Framework    : ionic-angular 3.9.2
>    @ionic/app-scripts : 3.1.10
> 
> Cordova:
> 
>    cordova (Cordova CLI) : 8.0.0
>    Cordova Platforms     : android 7.1.1, ios 4.5.4
>    Cordova Plugins       : cordova-plugin-ionic-keyboard 2.0.5, cordova-plugin-ionic-webview 1.1.1, (and 15 other plugins)
> 
> System:
> 
>    Android SDK Tools : 26.1.1 (/Users/anandmahajan/Library/Android/sdk)
>    ios-deploy        : 1.9.4
>    NodeJS            : v8.11.1 (/usr/local/bin/node)
>    npm               : 5.6.0
>    OS                : macOS High Sierra
>    Xcode             : Xcode 9.2 Build version 9C40b

Please suggest me some solution to overcome this issue. 

Thanks in advance.

**Comment by chemerisuk** [comment]
Better to ask ionic team.
