### ISSUE TITLE
Failed to install 'cordova-plugin-firebase-dynamiclinks':Error: Variable(s) missing: APP_DOMAIN, APP_PATH

### ISSUE THREAD

**Issue by Tarekajaj** [chemerisuk/cordova-plugin-firebase-dynamiclinks#3]

**Comment by Tarekajaj** [comment]
I was able to isntall using 
`cordova plugin add cordova-plugin-firebase-dynamiclinks --variable APP_DOMAIN="example.com" --variable APP_PATH="/"`

**Comment by litch** [comment]
I had the same issue - not sure how to configure this *correctly*, but that workaround seems ok...

**Comment by litch** [comment]
BTW, it looks like the "APP_DOMAIN" should be your Dynamic Link Domain: `https://<xxxxx>.app.goo.gl/`

You can find it here: https://console.firebase.google.com/project/<project-name>/durablelinks/links/

**Comment by chemerisuk** [comment]
Sorry for confusion - I've updated readme to clarify variables sense. Though I feel like those variables will be dropped soon.

**Comment by Tarekajaj** [comment]
Thanks
