### ISSUE TITLE
Dynamic link not recognized when app is being launched

### ISSUE THREAD

**Issue by rtm** [chemerisuk/cordova-plugin-firebase-dynamiclinks#3]
This is working fine when the app is already open, and a dynamic link is invoked somewhere, but not when the app needs to be launched, or when opening after installing. I think it's because the logic to listen to the links is not set up in time for the first ping. Is this a known problem and is there a known approach? In case it matters, I have an Angular app.

**Comment by remisture** [comment]
I have the same problem.

**Comment by cmartin81** [comment]
I also have the same problem
:(
Have you found a solution for the yet?

**Comment by adamschnaare** [comment]
Same issue here. Any thoughts?  I have the following in a plain js file at the top of my index and it still seems to not trigger the logic in time:

```js
document.addEventListener('deviceready', function() {
  window.cordova.plugins.firebase.dynamiclinks.onDynamicLink(function(data) {
  ...
 }
})
```

**Comment by Chuckv01** [comment]
Has anyone been able to get dynamic links persisting through the app install process on iOS using this plugin?

**Comment by AndreasGassmann** [comment]
I've had no luck so far. I would love to hear from someone who managed to get it working.

**Comment by Chuckv01** [comment]
I've gotten it working on my fork: https://github.com/Chuckv01/cordova-plugin-firebase-dynamiclinks

**Comment by AndreasGassmann** [comment]
That's good to hear. Sadly it also doesn't work with your fork (it does solve my problem with cordova-android 6.3, thanks for that 👍).

When adding the debug code from firebase, I get the following errors:

```
---- Firebase Dynamic Links diagnostic output start ----
Firebase Dynamic Links framework version 3.0.1
System information: OS iOS, OS version 11.2.6, model iPhone
Current date 2018-08-06 03:47:11 +0000
Device locale en-CH (raw en_CH), timezone Europe/Zurich
ERROR: UIApplication delegate <AppDelegate: 0x1c4225240> does not implements selector application:openURL:options:. FDL depends on this implementation to retrieve pending dynamic link.
ERROR: Specified custom URL scheme is dlscheme but Info.plist do not contain such scheme in CFBundleURLTypes key.
	AppID Prefix: xxx, Team ID: xxx, AppId Prefix equal to Team ID: YES
performDiagnostic detected 2 ERRORS.
---- Firebase Dynamic Links diagnostic output end ----
```
I tried it in 2 different apps, in both cases it didn't work. However in one (where I have the ionic-plugin-deeplinks installed), I only get the first error, but not the second one.

Any idea what's going on? Thanks a lot for your help!

**Comment by AndreasGassmann** [comment]
@Chuckv01 Is your app, or any app, that supports dynamic links on iOS available in the App Store? I would really like to see the flow in a working app because I have not been able to get it to work in any of my apps.

**Comment by alfazjikani** [comment]
Hi,

I got working by following below steps.

1. Load plugin at initial stage. 
< param name="onload" value="true" />

[plugin.txt](https://github.com/chemerisuk/cordova-plugin-firebase-dynamiclinks/files/3112186/plugin.txt)

2. AppDelegate+FirebaseDynamicLinksPlugin.m
-When app is launched, below instruction doesn't give expected output so I applied a workaround.
Actual Code:
**FirebaseDynamicLinksPlugin* dl = [self.viewController getCommandInstance:@"FirebaseDynamicLinks"];**

Modified Code:
**__block FirebaseDynamicLinksPlugin* dl = [self.viewController getCommandInstance:@"FirebaseDynamicLinks"];**
(Part1)

**if(dl == nil) {             
  dl = [self.viewController getCommandInstance:@"FirebaseDynamicLinks"];
}**
(Part2)

[AppDelegate+FirebaseDynamicLinksPlugin.txt](https://github.com/chemerisuk/cordova-plugin-firebase-dynamiclinks/files/3112039/AppDelegate%2BFirebaseDynamicLinksPlugin.txt)

3. FirebaseDynamicLinksPlugin.m
-remove handleOpenURL method from file as it has no use for now.

[FirebaseDynamicLinksPlugin.txt](https://github.com/chemerisuk/cordova-plugin-firebase-dynamiclinks/files/3112041/FirebaseDynamicLinksPlugin.txt)

I have attached files for reference.

**Comment by MrDrProfX** [comment]
Thanks @alfazjikani, it worked. I hope this bug actually get's fixed properly though.

**Comment by rajashekaranugu** [comment]
@MrDrProfX @alfazjikani,can you please share the steps you followed in using this plugin,

I have created the dynamic links using firebase console and added this plugin but my app stops at splashscreen itself. If I remove this plugin it works well

**Comment by rajashekaranugu** [comment]
> Thanks @alfazjikani, it worked. I hope this bug actually get's fixed properly though.
I have created the dynamic links using firebase console and added this plugin but my app stops at splashscreen itself. If I remove this plugin it works well

**Comment by MrDrProfX** [comment]
I simply followed the installation instructions in the readme. You may want to try `ionic repair --cordova` then rebuilding `ionic cordova build iOS`.

**Comment by rajashekaranugu** [comment]
> I simply followed the installation instructions in the readme. You may want to try `ionic repair --cordova` then rebuilding `ionic cordova build iOS`.

Hi thanks a lot, which version of cordova, cordova-ios and cordova android are you using
 Am on 
$ ionic info

Ionic:

   ionic (Ionic CLI)  : 4.5.0
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.4

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-webview 1.2.1, (and 21 other plugins)

System:

   ios-deploy : 1.9.4
   NodeJS     : v10.16.3 (/usr/local/bin/node)
   npm        : 6.12.0
   OS         : macOS Mojave
   Xcode      : Xcode 11.1 Build version 11A1027

**Comment by MrDrProfX** [comment]
ionic info

Ionic:

   Ionic CLI          : 5.4.4 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.1

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : android 8.1.0, ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 1.2.1, (and 9 other plugins)

Utility:

   cordova-res : 0.7.0 (update available: 0.8.1)
   native-run  : 0.2.9 

System:

   ios-deploy        : 1.9.4
   ios-sim           : 8.0.2
   NodeJS            : v10.15.3 (/usr/local/bin/node)
   npm               : 6.4.1
   OS                : macOS Catalina
   Xcode             : Xcode 11.0 Build version 11A420a

**Comment by rajashekaranugu** [comment]
> ionic info
> 
> Ionic:
> 
> Ionic CLI : 5.4.4 (/usr/local/lib/node_modules/ionic)
> Ionic Framework : ionic-angular 3.9.2
> @ionic/app-scripts : 3.2.1
> 
> Cordova:
> 
> Cordova CLI : 8.1.2 (cordova-lib@8.1.1)
> Cordova Platforms : android 8.1.0, ios 5.0.1
> Cordova Plugins : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 1.2.1, (and 9 other plugins)
> 
> Utility:
> 
> cordova-res : 0.7.0 (update available: 0.8.1)
> native-run : 0.2.9
> 
> System:
> 
> ios-deploy : 1.9.4
> ios-sim : 8.0.2
> NodeJS : v10.15.3 (/usr/local/bin/node)
> npm : 6.4.1
> OS : macOS Catalina
> Xcode : Xcode 11.0 Build version 11A420a

Hi Thanks a lot @MrDrProfX, Am on lower versions so I will update the cordova and check it. Thanks a lot
@Chuckv01 Chuckv01 can you please let us know what is the min corodva version to be

**Comment by rajashekaranugu** [comment]
@Chuckv01  please mention ionic info

**Comment by rajamuthur** [comment]
getDynamicLink() for getting dynamic link info on app start. 
onDynamicLink() callback is triggered only on subsequent calls

in ionc5:
platform.ready().then(() => {
  firebaseDynamicLinks.getDynamicLink().then((data) => {
  })
});
