### ISSUE TITLE
Android creating new webview for dynamic link

### ISSUE THREAD

**Issue by jacobg** [chemerisuk/cordova-plugin-firebase-dynamiclinks#30]
It looks like the Android implementation is creating a new webview when opening a dynamic link. For example, if my app is running, then I go to the Messages app and click on dynamic link, it reopens the app, and chrome://inspect shows two webviews running. Is this expected? I only want one webview running, so is there a way to do that?

**Comment by jacobg** [comment]
The solution is in config.xml to set:
`<preference name="AndroidLaunchMode" value="singleTask" />`

**Comment by chemerisuk** [comment]
Added a note to README about this https://github.com/chemerisuk/cordova-plugin-firebase-dynamiclinks/commit/eb7931852a6dfc4bf15de0f0a2a44528f1afbf53

**Comment by chemerisuk** [comment]
Fixed in https://github.com/chemerisuk/cordova-plugin-firebase-dynamiclinks/commit/43439ba53d2c6f101ede476f306bb27e6e2e0b7f
