### ISSUE TITLE
Failed to apply plugin [class 'com.google.gms.googleservices.GoogleServicesPlugin']

### ISSUE THREAD

**Issue by dineshpatra** [chemerisuk/cordova-plugin-firebase-dynamiclinks#31]
Hi,
I am trying to build for android after installing cordova-plugin-firebase-dynamiclinks plugin. but it throws error.
The error is as follows.

> Error: /Users/user1/ionicProject/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.
>
> * Where:
Script '/Users/user1/ionicProject/platforms/android/cordova-support-google-services/www-build.gradle' line: 16
>
> * What went wrong:
> A problem occurred evaluating root project 'android'.
> Failed to apply plugin [class 'com.google.gms.googleservices.GoogleServicesPlugin']
   > For input string: "+"
 
But it is building successfully without this plugin.

currently installed plugin list:

> cordova plugin list

	com.darktalker.cordova.screenshot 0.1.5 "Screenshot"
	cordova-plugin-admobpro 2.29.29 "AdMob Plugin Pro"
	cordova-plugin-camera 2.4.1 "Camera"
	cordova-plugin-compat 1.2.0 "Compat"
	cordova-plugin-email-composer 0.8.11 "EmailComposer"
	cordova-plugin-extension 1.5.3 "Cordova Plugin Extension"
	cordova-plugin-facebook4 1.9.1 "Facebook Connect"
	cordova-plugin-file 5.0.0 "File"
	cordova-plugin-file-opener2 2.0.19 "File Opener2"
	cordova-plugin-file-transfer 1.7.0 "File Transfer"
	cordova-plugin-firebase 0.1.25 "Google Firebase Plugin"
	cordova-plugin-inappbrowser 1.7.2 "InAppBrowser"
	cordova-plugin-network-information 1.3.4 "Network Information"
	cordova-plugin-splashscreen 4.1.0 "Splashscreen"
	cordova-plugin-statusbar 2.3.0 "StatusBar"
	cordova-plugin-whitelist 1.3.3 "Whitelist"
	cordova-plugin-wkwebview-engine 1.1.6 "Cordova WKWebView Engine"
	cordova-plugin-x-socialsharing 5.2.1 "SocialSharing"
	cordova-sqlite-storage 2.1.2 "Cordova sqlite storage plugin"
	cordova-support-google-services 1.0.0 "cordova-support-google-services"
	es6-promise-plugin 4.1.0 "Promise"
	ionic-plugin-keyboard 2.2.1 "Keyboard"

My ionic version details:

	cli packages: (/usr/local/lib/node_modules)

	    @ionic/cli-utils  : 1.18.0
	    ionic (Ionic CLI) : 3.18.0

	global packages:

	    cordova (Cordova CLI) : 7.1.0 

	local packages:

	    @ionic/app-scripts : 1.3.12
	    Cordova Platforms  : android 6.3.0
	    Ionic Framework    : ionic-angular 3.1.1

	System:

	    ios-deploy : 1.9.2 
	    ios-sim    : 5.0.13 
	    Node       : v6.10.3
	    npm        : 3.10.10 
	    OS         : macOS High Sierra
	    Xcode      : Xcode 9.1 Build version 9B55 

> cat /Users/user1/ionicProject/platforms/android/project.properties 

	# This file is automatically generated by Android Tools.
	# Do not modify this file -- YOUR CHANGES WILL BE ERASED!
	#
	# This file must be checked in Version Control Systems.
	#
	# To customize properties used by the Ant build system edit
	# "ant.properties", and override values to adapt the script to your
	# project structure.
	#
	# To enable ProGuard to shrink and obfuscate your code, uncomment this (available properties: sdk.dir, user.home):
	#proguard.config=${sdk.dir}/tools/proguard/proguard-android.txt:proguard-project.txt
	# Project target.
	target=android-26
	android.library.reference.1=CordovaLib
	cordova.system.library.1=com.google.android.gms:play-services-ads:+
	cordova.system.library.2=com.android.support:support-v4:24.1.1+
	cordova.system.library.3=com.android.support:support-v4:24.1.1+
	cordova.system.library.4=com.facebook.android:facebook-android-sdk:4.+
	cordova.system.library.5=com.android.support:support-v4:+
	cordova.gradle.include.1=cordova-plugin-firebase/www-build.gradle
	cordova.system.library.6=com.google.gms:google-services:+
	cordova.system.library.7=com.google.android.gms:play-services-tagmanager:+
	cordova.system.library.8=com.google.firebase:firebase-core:+
	cordova.system.library.9=com.google.firebase:firebase-messaging:+
	cordova.system.library.10=com.google.firebase:firebase-crash:+
	cordova.system.library.11=com.google.firebase:firebase-config:+
	cordova.system.library.12=com.android.support:support-v4:24.1.1+ 

Please help, totally stuck on this issue.

**Comment by chemerisuk** [comment]
@dineshpatra https://github.com/chemerisuk/cordova-support-google-services#build-error-failed-to-apply-plugin-class-comgooglegmsgoogleservicesgoogleservicesplugin

**Comment by chinlun** [comment]
@chemerisuk I am unsure how to fix this, below is my project.properties

> target=android-26
> android.library.reference.1=CordovaLib
> cordova.system.library.1=com.facebook.android:facebook-android-sdk:4.+
> cordova.gradle.include.1=cordova-plugin-firebase/app-build.gradle
> cordova.system.library.2=com.google.gms:google-services:+
> cordova.system.library.3=com.google.android.gms:play-services-tagmanager:+
> cordova.system.library.4=com.google.firebase:firebase-core:+
> cordova.system.library.5=com.google.firebase:firebase-messaging:+
> cordova.system.library.6=com.google.firebase:firebase-crash:+
> cordova.system.library.7=com.google.firebase:firebase-config:+
> cordova.system.library.8=com.google.android.gms:play-services-analytics:+
> cordova.gradle.include.2=cordova-support-google-services/app-build.gradle

**Comment by chemerisuk** [comment]
@chinlun https://github.com/chemerisuk/cordova-support-google-services#build-error-failed-to-apply-plugin-class-comgooglegmsgoogleservicesgoogleservicesplugin

**Comment by chinlun** [comment]
@chemerisuk I changed following lines to 11.0+, still can't get it to work.

cordova.system.library.2=com.google.gms:google-services:11.0.+
cordova.system.library.8=com.google.android.gms:play-services-analytics:11.0.+

Is there anything I missed?

**Comment by wilfredonoyola** [comment]
@chinlun @chinlun I have same problem, Do you know any fix for this?

Thanks

**Comment by wilfredonoyola** [comment]
I have tried some solutions, still can't get it to work. Maybe I will move to other plugin.

Thanks.
