### ISSUE TITLE
Camera usage description overwrites already existing camera usage description on iOS

### ISSUE THREAD

**Issue by Luukschoen** [chemerisuk/cordova-plugin-firebase-dynamiclinks#32]
First of all, thank you for your work on this plugin!

I tried to use it last week and I've encountered a couple of issues. The first one has to do with the camera usage description. My console keeps telling me it's mandatory, so I added a description while adding the plugin. Problem is it already existed in my project and now overwrites the first description. I think we should somehow check if it already exists in our configuration and skip it if it's already there. 

What do you think?

**Comment by chemerisuk** [comment]
Try to use v0.12.0. I dropped invites related logic there
