### ISSUE TITLE
Issue with prod building on Ionic

### ISSUE THREAD

**Issue by JerryBels** [chemerisuk/cordova-plugin-firebase-dynamiclinks#32]
I have a VERY strange bug which I have absolutely no idea how to debug.

When building my ionic app and launching on my Android, it works just fine. But, when I add the --prod flag - which I do every time I want to show something to the customer - I have that angular error :

```
 main.5e301c2a6dc3a49ec613.js:1 ERROR Error: StaticInjectorError[t -> e]: 
  StaticInjectorError(Platform: core)[t -> e]: 
    NullInjectorError: No provider for e!
    at t.get (main.5e301c2a6dc3a49ec613.js:1)
    at main.5e301c2a6dc3a49ec613.js:1
    at t (main.5e301c2a6dc3a49ec613.js:1)
    at t.get (main.5e301c2a6dc3a49ec613.js:1)
    at main.5e301c2a6dc3a49ec613.js:1
    at t (main.5e301c2a6dc3a49ec613.js:1)
    at t.get (main.5e301c2a6dc3a49ec613.js:1)
    at oi (main.5e301c2a6dc3a49ec613.js:1)
    at t.get (main.5e301c2a6dc3a49ec613.js:1)
    at Qi (main.5e301c2a6dc3a49ec613.js:1)
```

And the app doesn't load at all, remains blank. Not very helpfull - which is expected since it's --prod. 

When it becomes interesting, it's that whenever I remove the `cordova-plugin-firebase-dynamiclinks` from `app.component`, everything works perfectly. What gives ? Why is there a problem with the plugin under prod env ?

**Comment by chinib** [comment]
Don't forget to add

**Comment by ben-kn-app** [comment]
Did you add FirebaseDynamicLinks to the providers of your app.module? Otherwise you would get such a staticInjectError.

```
 providers: [
        FirebaseDynamicLinks,
        ...
    ],
```

**Comment by skout90** [comment]
@chinib thanks. I solved same problem.
