### ISSUE TITLE
deepLink always returning empty

### ISSUE THREAD

**Issue by dineshpatra** [chemerisuk/cordova-plugin-firebase-dynamiclinks#34]
I am trying to build deeplink concept using firebase dynamic link. But when ever I am trying to open the app using the manually constructed (also the short url) dynamic url, in ios I am getting

    {"matchType": "weak", "deepLink":""}

But the same code is working on android.

My ionic info.

    cli packages: (/usr/local/lib/node_modules)

        @ionic/cli-utils  : 1.18.0
        ionic (Ionic CLI) : 3.18.0

    global packages:

        cordova (Cordova CLI) : 7.1.0 

    local packages:

        @ionic/app-scripts : 1.3.12
        Cordova Platforms  : android 6.3.0 ios 4.5.4
        Ionic Framework    : ionic-angular 3.1.1

    System:

        ios-deploy : 1.9.2 
        ios-sim    : 5.0.13 
        Node       : v9.2.1
        npm        : 3.10.10 
        OS         : macOS High Sierra
        Xcode      : Xcode 9.1 Build version 9B55 

my installed plugin list

    com.darktalker.cordova.screenshot 0.1.5 "Screenshot"
    cordova-plugin-admobpro 2.29.29 "AdMob Plugin Pro"
    cordova-plugin-camera 2.4.1 "Camera"
    cordova-plugin-compat 1.2.0 "Compat"
    cordova-plugin-email-composer 0.8.11 "EmailComposer"
    cordova-plugin-extension 1.5.3 "Cordova Plugin Extension"
    cordova-plugin-facebook4 1.9.1 "Facebook Connect"
    cordova-plugin-file 5.0.0 "File"
    cordova-plugin-file-opener2 2.0.19 "File Opener2"
    cordova-plugin-file-transfer 1.7.0 "File Transfer"
    cordova-plugin-firebase 0.1.25 "Google Firebase Plugin"
    cordova-plugin-firebase-dynamiclinks 0.10.1 "FirebaseDynamicLinksPlugin"
    cordova-plugin-inappbrowser 1.7.2 "InAppBrowser"
    cordova-plugin-network-information 1.3.4 "Network Information"
    cordova-plugin-splashscreen 4.1.0 "Splashscreen"
    cordova-plugin-statusbar 2.3.0 "StatusBar"
    cordova-plugin-whitelist 1.3.3 "Whitelist"
    cordova-plugin-wkwebview-engine 1.1.6 "Cordova WKWebView Engine"
    cordova-plugin-x-socialsharing 5.2.1 "SocialSharing"
    cordova-sqlite-storage 2.1.4 "Cordova sqlite storage plugin"
    cordova-support-google-services 1.0.0 "cordova-support-google-services"
    es6-promise-plugin 4.1.0 "Promise"
    ionic-plugin-keyboard 2.2.1 "Keyboard"

Also https://xxxxx.app.goo.gl/apple-app-site-association, https://xxxxx.app.goo.gl/.well-known/apple-app-site-association are looking fine.

my manually constructed dynamic link:

https://xxxxx.app.goo.gl/?link=<encoded url to my web page with https protocol>&ibi=(ios bundle id)&apn=(android bundle id)

I am trying to open the link in iPhone4s (ios9.1.3).
But in log its telling:

{"matchType": "weak", "deepLink":""}

I have enabled associated domain under capabilities se ction, and there I have mentioned 
applinks:xxxxx.app.goo.gl

pod version: 1.3.1

    this.platform.ready()
    .then(() => {  
        return this.firebaseDynamicLinks.onDynamicLink()
        .then((dynamicLink: any) => { 
            console.log(dynamicLink);   // returning {"matchType": "weak", "deepLink":""}, but in android, its working fine.
            this.dynamic_link = dynamicLink.deepLink; 
            return Promise.resolve("ok");
        }).catch((firebaseError: any) => {   
            console.error(firebaseError); 
            return Promise.resolve("ok");
        });
    })

Please help. Totally stuck here. Unable to release.
Thank you in advance.

**Comment by aaronneon2** [comment]
Investigation into this issue shows that
`- (BOOL)identity_application:(UIApplication *)application
        continueUserActivity:(NSUserActivity *)userActivity
          restorationHandler:(void (^)(NSArray *))restorationHandler {`
was not run thus the dynamic link is not handled.

Can contributors please look into this issue? This plugin is not working.
I am testing it with a iPhone6+ running iOS 11.1.1.  Using ionic 3.

**Comment by adamduren** [comment]
@aaronneon2 I believe that may be a different issue. He's getting the callback called so I believe that would suggest that the code is getting ran. I've experience the issue you've mentioned and there is an MR to fix it here. https://github.com/chemerisuk/cordova-plugin-firebase-dynamiclinks/pull/39

**Comment by chemerisuk** [comment]
Firebase Dynamic Links SDK has [unresolved bug](https://github.com/firebase/firebase-ios-sdk/issues/233) related to parsing `deepLink` for new app installs. It order to get it work your dynamic link MUST have [app preview page](https://firebase.google.com/docs/dynamic-links/link-previews), which is the default setting.
