### ISSUE TITLE
Dynamic Link Event on Install/Open

### ISSUE THREAD

**Issue by carliblaz** [chemerisuk/cordova-plugin-firebase-dynamiclinks#35]
Hi, I can't find this in the documentation. One of Dynamic Links option is tracking installs from invited users - users that download the app via dynamic link. Is there any event with payload after install or. first opening?

Thanks!

**Comment by Rajdev2011** [comment]
Hi @carliblaz any luck how you implemented this. iam have same issue 
how we can track the   signup when they are invited through dynamic link.

**Comment by chemerisuk** [comment]
AFAIK no, firebase does not provide such data.
