### ISSUE TITLE
Ionic ios build failed

### ISSUE THREAD

**Issue by dagovalsusa** [chemerisuk/cordova-plugin-firebase-dynamiclinks#36]
Hello, after install the plugin ionic project can't compile cause:

The following build commands failed:
        CompileC Developer/Xcode/DerivedData/AWorld-cafcuqysjdzagnbvkvdpdyohacrh/Build/Intermediates.noindex/AWorld.build/Debug-iphonesimulator/AWorld.build/Objects-normal/x86_64/FirebaseDynamicLinksPlugin.o platforms/ios/AWorld/Plugins/cordova-plugin-firebase-dynamiclinks/FirebaseDynamicLinksPlugin.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
xcodebuild: Command failed with exit code 65

another error on compile process is

/cordova-plugin-firebase-dynamiclinks/FirebaseDynamicLinksPlugin.h:4:9: fatal error: module 'Firebase' not found
@import Firebase;

here my ionic info

Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.4.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.4.1

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4, browser 5.0.4, ios 5.0.1
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.2, (and 18 other plugins)

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.1
   NodeJS     : v10.15.3 (/usr/local/bin/node)
   npm        : 6.9.0
   OS         : macOS Mojave
   Xcode      : Xcode 10.2.1 Build version 10E1001

I've already try to install firebase plugin but compile fail with another error
(from xcode)
ARC Semantic Issue
/Plugins/cordova-plugin-firebase/FirebasePlugin.m:117:47: No visible @interface for 'FIRMessaging' declares the selector 'setDelegate:'

**Comment by chemerisuk** [comment]
I've forced cordova >= 9.0.0 in v2.0.4

**Comment by walmon** [comment]
I get the same error @dagovalsusa did you manage to solve this? I have the latest versions of everything
