### ISSUE TITLE
error installing plugin: Error: CocoaPods was not found. Please install version 1.0.1

### ISSUE THREAD

**Issue by alphapilgrim** [chemerisuk/cordova-plugin-firebase-dynamiclinks#36]
Installing "cordova-plugin-firebase-dynamiclinks" for iosFailed to install 'cordova-plugin-firebase-dynamiclinks': undefined
Error: CocoaPods was not found. Please install version 1.0.1 or greater from https://cocoapods.org/

[ERROR] An error occurred while running cordova plugin add cordova-plugin-firebase-dynamiclinks --variable
        APP_DOMAIN=ho... (exit code 1).

**Comment by silverio** [comment]
try `sudo gem install cocoapods` and then `pod repo update`
