### ISSUE TITLE
Dynamic Link Parameters

### ISSUE THREAD

**Issue by mateusduraes** [chemerisuk/cordova-plugin-firebase-dynamiclinks#37]
Hi!

I don't know if it is a real issue, but i didn't find a helpful content on the web about how to work with parameters in a Firebase Dynamic Link

My question is:

How can i use a parameter / query string with this plugin? Is it possible?

I have a dynamic link and it is working very well.

If the app is installed, it opens the app, otherwise it opens the app store, great!

My link is just like the following:
https://techbusinesshub.page.link/feed

I need to use something like:
https://techbusinesshub.page.link/feed?contentId=23

But when I do it I am not able to receive the parameters in the plugin callback. It opens the app but not gives me the parameters. 

The output in my callback is like the following:
```typescript
{
  clickTimestamp: 1559584054784,
  deepLink: "https://techbusinesshub.page.link",
  minimumAppVersion: 0
}
```
Can you help me? Thanks.

**Comment by igorgidea** [comment]
Hi, same issue here, cant get passed custom params, need help!

**Comment by chemerisuk** [comment]
Append a query string to parameter `deepLink`:
```
{
deepLink: "https://techbusinesshub.page.link?foo=bar",
}
```

**Comment by CesarGalindoSalgado** [comment]
Hi guys, Were you able to get the parameters? I have the same issue but I think I'm missing something.

**Comment by mateusduraes** [comment]
Hi @CesarGalindoSalgado, for me, it only works if you get the detail link in firebase.

I'll try to help you. Did you create the link inside the firebase dashboard? If the answer is yes, access the detail of the link and get the full link.

If you have created a link like:
https://techbusinesshub.page.link/content

The full link should look like:
https://techbusinesshub.page.link/?link=https://techbusinesshub.page.link/content&apn=yourappid&isi=id&ibi=appid

So, programmatically I get this full link and add the dynamic information, then it will look like:
https://techbusinesshub.page.link/?link=https://techbusinesshub.page.link/content/21&apn=yourappid&isi=id&ibi=appid



In my App, I'm able to get this information and extract the id "21" from the string.

Good luck

**Comment by NLueg** [comment]
Hi all, I currently struggle with the same issue.
@mateusduraes unfortunately, I can't get the additional information with the `onDynamicLink` method. I only get the 'basic' URL as you described at the beginning of this issue.

Do you use the same method to retrieve the full link?
