### ISSUE TITLE
capacitor Module 'Firebase' not found

### ISSUE THREAD

**Issue by oliverandersencox** [chemerisuk/cordova-plugin-firebase-dynamiclinks#39]
I have tired many times to install and use this with capacitor.

No matter which pods or packages I install I am always getting this error:

> Module 'Firebase' not found

Anyone have any success with capacitor and this?

**Comment by mathew-n27** [comment]
Same error in Xcode when using this plugin on Cordova Ionic 4 app. Is there a fix?

**Comment by oliverandersencox** [comment]
https://github.com/ionic-team/capacitor/pull/1712 about to give this a go - will let you know if it works

**Comment by brindha-adpl** [comment]
@oliverandersencox how to integrate this plugin with capacitor project? I have added this but i have this warning. And i can't able to get it work

`<dict>
      <key>CFBundleTypeRole</key>
      <key>CFBundleURLName</key>
      <key>CFBundleURLSchemes</key>
      <string>Editor</string>
      <string>BUNDLE_ID</string>
      <array>
        <string>$PACKAGE_NAME</string>
      </array>
    </dict>
   in the existing CFBundleURLTypes entry of your Info.plist to work`

kindly advice

**Comment by chemerisuk** [comment]
Better to ask capacitor team.
