### ISSUE TITLE
iOS open app but does not fire onDynamicLink

### ISSUE THREAD

**Issue by Tarekajaj** [chemerisuk/cordova-plugin-firebase-dynamiclinks#4]

**Comment by Tarekajaj** [comment]
It seems it's not compatible with "cordova-universal-links-plugin".

**Comment by Tarekajaj** [comment]
I added the following to **AppDelegate+FirebaseDynamicLinks.m**  at the end before `return handled;`
```
if(!handled){
      [dl sendDynamicLinkData:@{
          @"deepLink": userActivity.webpageURL.absoluteURL.absoluteString,
          @"matchType": @"None"
          }];
  }
```
this will trigger onDynamicLink for any link that opens the app. any better solution is welcomed.

**Comment by Stukongeluk** [comment]
Hm I still haven't got it to work, even with your code. The link opens the app but does not fire the implementation on onDynamicLink.

**Comment by premtemp1** [comment]
I tried adding the code...

 if(!handled){
        [dl sendDynamicLinkData:@{
                                  @"deepLink": userActivity.webpageURL.absoluteURL.absoluteString,
                                  @"matchType": @"None"
                                  }];
    }
and i get the error
No visible @interface for 'FirebaseDynamicLinksPlugin' declares the selector 'sendDynamicLinkData:'

Am I adding it correctly...

This is actual function

/ [START continueuseractivity]
- (BOOL)identity_application:(UIApplication *)application
        continueUserActivity:(NSUserActivity *)userActivity
          restorationHandler:(void (^)(NSArray *))restorationHandler {
    FirebaseDynamicLinksPlugin* dl = [self.viewController getCommandInstance:@"FirebaseDynamicLinks"];
 
    BOOL handled = [[FIRDynamicLinks dynamicLinks]
        handleUniversalLink:userActivity.webpageURL
        completion:^(FIRDynamicLink * _Nullable dynamicLink, NSError * _Nullable error) {
            // Try this method as some dynamic links are not recognize by handleUniversalLink
            // ISSUE: https://github.com/firebase/firebase-ios-sdk/issues/743
            dynamicLink = dynamicLink ? dynamicLink
                : [[FIRDynamicLinks dynamicLinks]
                   dynamicLinkFromUniversalLinkURL:userActivity.webpageURL];
            
            if (dynamicLink) {
                [dl postDynamicLink:dynamicLink];
            }
        }];

  
    if (handled) {
        return YES;
    }

    if(!handled){
        [dl sendDynamicLinkData:@{
                                  @"deepLink": userActivity.webpageURL.absoluteURL.absoluteString,
                                  @"matchType": @"None"
                                  }];
    }
    return [self identity_application:application
                 continueUserActivity:userActivity
                   restorationHandler:restorationHandler];
}
// [END continueuseractivity]


Thanks

**Comment by kunalkakkad** [comment]
Hello,

I am facing the same problem i.e. app is opening but dynamiclink method is not called.

I had tried to put the code but i am also facing the same error as of @premtemp1 is facing.
Kindly guide us what is to be done to achieve the same.

Thanks in advance.
Kunal Kakkad
