### ISSUE TITLE
Ios build issue after installing dynamic link plugin.

### ISSUE THREAD

**Issue by vc-hitesh** [chemerisuk/cordova-plugin-firebase-dynamiclinks#4]
Ld /Users/vc-pc-39/Library/Developer/Xcode/DerivedData/The_Xavier\'s_Connect-azijmyzvyjbdejdvqzpggfsfvxqv/Build/Intermediates.noindex/txc.build/Release-iphonesimulator/txc.build/Objects-normal/i386/txc normal i386
    cd "/Users/vc-pc-39/Documents/Project/new-clone/app/platforms/ios"
    export IPHONEOS_DEPLOYMENT_TARGET=9.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/vc-pc-39/Documents/Project/new-clone/firebase-chatapp/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Frameworks/Mono.framework/Versions/Current/Commands"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch i386 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.3.sdk -L/Users/vc-pc-39/Documents/Project/new-clone/firebase-chatapp/platforms/ios/build/emulator -L/Users/vc-pc-39/Library/Developer/Xcode/DerivedData/The_Xavier\'s_Connect-azijmyzvyjbdejdvqzpggfsfvxqv/Build/Products/Release-iphonesimulator/GoogleToolboxForMac -L/Users/vc-pc-39/Library/Developer/Xcode/DerivedData/The_Xavier\'s_Connect-azijmyzvyjbdejdvqzpggfsfvxqv/Build/Products/Release-iphonesimulator/nanopb -F/Users/vc-pc-39/Documents/Project/new-clone/firebase-chatapp/platforms/ios/build/emulator -F/Users/vc-pc-39/Documents/Project/new-clone/firebase-chatapp/platforms/ios/Pods/FirebaseAnalytics/Frameworks -F/Users/vc-pc-39/Documents/Project/new-clone/firebase-chatapp/platforms/ios/Pods/FirebaseCore/Frameworks -F/Users/vc-pc-39/Documents/Project/new-clone/firebase-chatapp/platforms/ios/Pods/FirebaseDynamicLinks/Frameworks -F/Users/vc-pc-39/Documents/Project/new-clone/firebase-chatapp/platforms/ios/Pods/FirebaseInstanceID/Frameworks -Ftxc/Plugins/cordova-plugin-firebase -filelist /Users/vc-pc-39/Library/Developer/Xcode/DerivedData/The_Xavier\'s_Connect-azijmyzvyjbdejdvqzpggfsfvxqv/Build/Intermediates.noindex/txc.build/Release-iphonesimulator/The\ Xavier\'s\Connect.build/Objects-normal/i386/txc.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -mios-simulator-version-min=9.0 -dead_strip -Xlinker -object_path_lto -Xlinker /Users/vc-pc-39/Library/Developer/Xcode/DerivedData/The_Xavier\'s_Connect-azijmyzvyjbdejdvqzpggfsfvxqv/Build/Intermediates.noindex/txc.build/Release-iphonesimulator/txc.build/Objects-normal/i386/txc_lto.o -Xlinker -objc_abi_version -Xlinker 2 -fobjc-arc -fobjc-link-runtime -ObjC -ObjC -lGoogleToolboxForMac -lc++ -lnanopb -lsqlite3 -lz -framework AssetsLibrary -framework FirebaseAnalytics-framework FirebaseCore -framework FirebaseCoreDiagnostics -framework FirebaseDynamicLinks -framework FirebaseInstanceID -framework FirebaseNanoPB -framework MessageUI -framework QuartzCore -framework StoreKit -framework SystemConfiguration -weak_framework WebKit -ObjC -lGoogleToolboxForMac -lc++ -lnanopb -lsqlite3 -lz -framework AssetsLibrary -framework FirebaseAnalytics -framework FirebaseCore -framework FirebaseCoreDiagnostics -framework FirebaseDynamicLinks -framework FirebaseInstanceID -framework FirebaseNanoPB -framework MessageUI -framework QuartzCore -framework StoreKit -framework SystemConfiguration -weak_framework WebKit -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/vc-pc-39/Library/Developer/Xcode/DerivedData/The_Xavier\'s_Connect-azijmyzvyjbdejdvqzpggfsfvxqv/Build/Intermediates.noindex/txc.build/Release-iphonesimulator/txc.build/txc.app-Simulated.xcent /Users/vc-pc-39/Documents/Project/new-clone/firebase-chatapp/platforms/ios/build/emulator/libCordova.a -weak_framework ImageIO -framework CoreLocation -framework AVFoundation -weak_framework WebKit -lz -weak_framework AddressBook -weak_framework AddressBookUI -framework MediaPlayer -framework CoreVideo -weak_framework Social-weak_framework MessageUI -framework UserNotifications -framework FirebaseAnalytics -framework FirebaseCore -framework FirebaseCoreDiagnostics -framework FirebaseInstanceID -framework FirebaseNanoPB -framework GoogleToolboxForMac -framework nanopb -framework Protobuf -framework FirebaseMessaging -framework FirebaseCrash -framework FirebaseRemoteConfig -framework FirebaseABTesting -framework FirebaseAuth -framework GTMSessionFetcher-framework FirebasePerformance -framework FirebaseISASwizzler -framework FirebaseMethodSwizzler -lPods-txc -Xlinker -dependency_info -Xlinker /Users/vc-pc-39/Library/Developer/Xcode/DerivedData/The_Xavier\'s_Connect-azijmyzvyjbdejdvqzpggfsfvxqv/Build/Intermediates.noindex/txc.build/Release-iphonesimulator/txc.build/Objects-normal/i386/txc_dependency_info.dat -o /Users/vc-pc-39/Library/Developer/Xcode/DerivedData/The_Xavier\'s_Connect-azijmyzvyjbdejdvqzpggfsfvxqv/Build/Intermediates.noindex/txc.build/Release-iphonesimulator/txc.build/Objects-normal/i386/txc
ld: warning: directory not found for option '-L/Users/vc-pc-39/Library/Developer/Xcode/DerivedData/The_Xavier's_Connect-azijmyzvyjbdejdvqzpggfsfvxqv/Build/Products/Release-iphonesimulator/GoogleToolboxForMac'
ld: warning: directory not found for option '-L/Users/vc-pc-39/Library/Developer/Xcode/DerivedData/The_Xavier's_Connect-azijmyzvyjbdejdvqzpggfsfvxqv/Build/Products/Release-iphonesimulator/nanopb'
duplicate symbol _OBJC_CLASS_$_PodsDummy_nanopb in:
    /Users/vc-pc-39/Documents/Project/new-clone/firebase-chatapp/platforms/ios/build/emulator/libnanopb.a(nanopb-dummy.o)
    The Xavier's Connect/Plugins/cordova-plugin-firebase/nanopb.framework/nanopb(nanopb-dummy.o)
duplicate symbol _OBJC_METACLASS_$_PodsDummy_nanopb in:
    /Users/vc-pc-39/Documents/Project/new-clone/firebase-chatapp/platforms/ios/build/emulator/libnanopb.a(nanopb-dummy.o)
    The Xavier's Connect/Plugins/cordova-plugin-firebase/nanopb.framework/nanopb(nanopb-dummy.o)
duplicate symbol _OBJC_CLASS_$_PodsDummy_GoogleToolboxForMac in:
    /Users/vc-pc-39/Documents/Project/new-clone/firebase-chatapp/platforms/ios/build/emulator/libGoogleToolboxForMac.a(GoogleToolboxForMac-dummy.o)
    The Xavier's Connect/Plugins/cordova-plugin-firebase/GoogleToolboxForMac.framework/GoogleToolboxForMac(GoogleToolboxForMac-dummy.o)
duplicate symbol _OBJC_METACLASS_$_PodsDummy_GoogleToolboxForMac in:
    /Users/vc-pc-39/Documents/Project/new-clone/firebase-chatapp/platforms/ios/build/emulator/libGoogleToolboxForMac.a(GoogleToolboxForMac-dummy.o)
    The Xavier's Connect/Plugins/cordova-plugin-firebase/GoogleToolboxForMac.framework/GoogleToolboxForMac(GoogleToolboxForMac-dummy.o)
ld: 7 duplicate symbols for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Ld /Users/vc-pc-39/Library/Developer/Xcode/DerivedData/The_Xavier\'s_Connect-azijmyzvyjbdejdvqzpggfsfvxqv/Build/Intermediates.noindex/txc.build/Release-iphonesimulator/txc.build/Objects-normal/x86_64/txc normal x86_64
    cd "/Users/vc-pc-39/Documents/Project/new-clone/firebase-chatapp/platforms/ios"
    export IPHONEOS_DEPLOYMENT_TARGET=9.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/vc-pc-39/Documents/Project/new-clone/firebase-chatapp/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Frameworks/Mono.framework/Versions/Current/Commands"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.3.sdk -L/Users/vc-pc-39/Documents/Project/new-clone/firebase-chatapp/platforms/ios/build/emulator -L/Users/vc-pc-39/Library/Developer/Xcode/DerivedData/The_Xavier\'s_Connect-azijmyzvyjbdejdvqzpggfsfvxqv/Build/Products/Release-iphonesimulator/GoogleToolboxForMac -L/Users/vc-pc-39/Library/Developer/Xcode/DerivedData/The_Xavier\'s_Connect-azijmyzvyjbdejdvqzpggfsfvxqv/Build/Products/Release-iphonesimulator/nanopb -F/Users/vc-pc-39/Documents/Project/new-clone/firebase-chatapp/platforms/ios/build/emulator -F/Users/vc-pc-39/Documents/Project/new-clone/firebase-chatapp/platforms/ios/Pods/FirebaseAnalytics/Frameworks -F/Users/vc-pc-39/Documents/Project/new-clone/firebase-chatapp/platforms/ios/Pods/FirebaseCore/Frameworks -F/Users/vc-pc-39/Documents/Project/new-clone/firebase-chatapp/platforms/ios/Pods/FirebaseDynamicLinks/Frameworks -F/Users/vc-pc-39/Documents/Project/new-clone/firebase-chatapp/platforms/ios/Pods/FirebaseInstanceID/Frameworks -Ftxc/Plugins/cordova-plugin-firebase -filelist /Users/vc-pc-39/Library/Developer/Xcode/DerivedData/The_Xavier\'s_Connect-azijmyzvyjbdejdvqzpggfsfvxqv/Build/Intermediates.noindex/txc.build/Release-iphonesimulator/txc.build/Objects-normal/x86_64/txc.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -mios-simulator-version-min=9.0 -dead_strip -Xlinker -object_path_lto -Xlinker /Users/vc-pc-39/Library/Developer/Xcode/DerivedData/The_Xavier\'s_Connect-azijmyzvyjbdejdvqzpggfsfvxqv/Build/Intermediates.noindex/txc.build/Release-iphonesimulator/txc.build/Objects-normal/x86_64/txc_lto.o -Xlinker -objc_abi_version -Xlinker 2 -fobjc-arc -fobjc-link-runtime -ObjC -ObjC -lGoogleToolboxForMac -lc++ -lnanopb -lsqlite3 -lz -framework AssetsLibrary -framework FirebaseAnalytics -framework FirebaseCore -framework FirebaseCoreDiagnostics -framework FirebaseDynamicLinks -framework FirebaseInstanceID -framework FirebaseNanoPB -framework MessageUI -framework QuartzCore -framework StoreKit -framework SystemConfiguration -weak_framework WebKit -ObjC -lGoogleToolboxForMac -lc++ -lnanopb -lsqlite3 -lz -framework AssetsLibrary -framework FirebaseAnalytics -framework FirebaseCore -framework FirebaseCoreDiagnostics -framework FirebaseDynamicLinks -framework FirebaseInstanceID -framework FirebaseNanoPB -framework MessageUI -framework QuartzCore -framework StoreKit -framework SystemConfiguration -weak_framework WebKit -Xlinker-sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/vc-pc-39/Library/Developer/Xcode/DerivedData/The_Xavier\'s_Connect-azijmyzvyjbdejdvqzpggfsfvxqv/Build/Intermediates.noindex/txc.build/Release-iphonesimulator/txc.build/txc.app-Simulated.xcent /Users/vc-pc-39/Documents/Project/new-clone/firebase-chatapp/platforms/ios/build/emulator/libCordova.a-weak_framework ImageIO -framework CoreLocation -framework AVFoundation -weak_framework WebKit -lz -weak_framework AddressBook -weak_framework AddressBookUI -framework MediaPlayer -framework CoreVideo -weak_framework Social -weak_framework MessageUI -framework UserNotifications -framework FirebaseAnalytics -framework FirebaseCore -framework FirebaseCoreDiagnostics -framework FirebaseInstanceID -framework FirebaseNanoPB -framework GoogleToolboxForMac -framework nanopb -framework Protobuf -framework FirebaseMessaging -framework FirebaseCrash -framework FirebaseRemoteConfig -framework FirebaseABTesting -framework FirebaseAuth -framework GTMSessionFetcher -framework FirebasePerformance -framework FirebaseISASwizzler -framework FirebaseMethodSwizzler -lPods-txc -Xlinker -dependency_info -Xlinker /Users/vc-pc-39/Library/Developer/Xcode/DerivedData/The_Xavier\'s_Connect-azijmyzvyjbdejdvqzpggfsfvxqv/Build/Intermediates.noindex/txc.build/Release-iphonesimulator/txc.build/Objects-normal/x86_64/txc_dependency_info.dat -o /Users/vc-pc-39/Library/Developer/Xcode/DerivedData/The_Xavier\'s_Connect-azijmyzvyjbdejdvqzpggfsfvxqv/Build/Intermediates.noindex/txc.build/Release-iphonesimulator/txc.build/Objects-normal/x86_64/txc
ld: warning: directory not found for option '-L/Users/vc-pc-39/Library/Developer/Xcode/DerivedData/The_Xavier's_Connect-azijmyzvyjbdejdvqzpggfsfvxqv/Build/Products/Release-iphonesimulator/GoogleToolboxForMac'
ld: warning: directory not found for option '-L/Users/vc-pc-39/Library/Developer/Xcode/DerivedData/The_Xavier's_Connect-azijmyzvyjbdejdvqzpggfsfvxqv/Build/Products/Release-iphonesimulator/nanopb'
duplicate symbol _OBJC_CLASS_$_PodsDummy_nanopb in:
    /Users/vc-pc-39/Documents/Project/new-clone/firebase-chatapp/platforms/ios/build/emulator/libnanopb.a(nanopb-dummy.o)
    The Xavier's Connect/Plugins/cordova-plugin-firebase/nanopb.framework/nanopb(nanopb-dummy.o)
duplicate symbol _OBJC_METACLASS_$_PodsDummy_nanopb in:
    /Users/vc-pc-39/Documents/Project/new-clone/firebase-chatapp/platforms/ios/build/emulator/libnanopb.a(nanopb-dummy.o)
    The Xavier's Connect/Plugins/cordova-plugin-firebase/nanopb.framework/nanopb(nanopb-dummy.o)
duplicate symbol _OBJC_CLASS_$_PodsDummy_GoogleToolboxForMac in:
    /Users/vc-pc-39/Documents/Project/new-clone/firebase-chatapp/platforms/ios/build/emulator/libGoogleToolboxForMac.a(GoogleToolboxForMac-dummy.o)
    The Xavier's Connect/Plugins/cordova-plugin-firebase/GoogleToolboxForMac.framework/GoogleToolboxForMac(GoogleToolboxForMac-dummy.o)
duplicate symbol _OBJC_METACLASS_$_PodsDummy_GoogleToolboxForMac in:
    /Users/vc-pc-39/Documents/Project/new-clone/firebase-chatapp/platforms/ios/build/emulator/libGoogleToolboxForMac.a(GoogleToolboxForMac-dummy.o)
    The Xavier's Connect/Plugins/cordova-plugin-firebase/GoogleToolboxForMac.framework/GoogleToolboxForMac(GoogleToolboxForMac-dummy.o)
ld: 7 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **

The following build commands failed:
        Ld /Users/vc-pc-39/Library/Developer/Xcode/DerivedData/The_Xavier\'s_Connect-azijmyzvyjbdejdvqzpggfsfvxqv/Build/Intermediates.noindex/txc.build/Release-iphonesimulator/txc.build/Objects-normal/i386/txc normal i386
        Ld /Users/vc-pc-39/Library/Developer/Xcode/DerivedData/The_Xavier\'s_Connect-azijmyzvyjbdejdvqzpggfsfvxqv/Build/Intermediates.noindex/txc.build/Release-iphonesimulator/txc.build/Objects-normal/x86_64/txc normal x86_64
(2 failures)
Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/vc-pc-39/Documents/Project/new-clone/firebase-chatapp/platforms/ios/cordova/build-release.xcconfig,-workspace,The Xavier's Connect.xcworkspace,-scheme,The Xavier's Connect,-configuration,Release,-sdk,iphonesimulator,-destination,platform=iOS Simulator,name=iPhone X,build,CONFIGURATION_BUILD_DIR=/Users/vc-pc-39/Documents/Project/new-clone/firebase-chatapp/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/vc-pc-39/Documents/Project/new-clone/firebase-chatapp/platforms/ios/build/sharedpch

[ERROR] An error occurred while running cordova build ios --release (exit code 1).

**Ionic Info:**
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-plugin-proxy : 1.5.8
    @ionic/cli-utils        : 1.19.2
    ionic (Ionic CLI)       : 3.20.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.2
    ios-sim    : 6.1.2
    Node       : v8.9.3
    npm        : 2.15.12
    OS         : macOS High Sierra
    Xcode      : Xcode 9.3 Build version 9E145

**Comment by atapias** [comment]
Hello,

I have the same issue, "duplicate symbols for architecture x86_64"

**Comment by chemerisuk** [comment]
Cordova cli issue. Open `platforms/ios/*.xcworkspace` and build from xcode.

**Comment by chemerisuk** [comment]
[PR with the fix for cordova cli](https://github.com/apache/cordova-ios/pull/398) was merged, so I believe the issue will be resolved in the next cordova-ios release.
