### ISSUE TITLE
Using "requireCordovaModule" to load non-cordova module "child_process" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.

### ISSUE THREAD

**Issue by PocoMin** [chemerisuk/cordova-plugin-firebase-dynamiclinks#40]
Cant compile IOS after download the latest plugin and upgrade angular to 9.0.0

This post (https://github.com/apache/cordova/issues/52#issuecomment-475696680) from Cordova mentioned "the error message is an attempt to communicate that we do not really want to support using "requireCordovaModule" to load non-Cordova module "q" any longer. We really recommend that you consider importing and requiring the q module in your own code"

**Comment by chemerisuk** [comment]
This plugin does not  have any hooks.
