### ISSUE TITLE
Plugin not installed

### ISSUE THREAD

**Issue by cmohanraj10** [chemerisuk/cordova-plugin-firebase-dynamiclinks#44]
I am building my application using Phonegap build. Here is my plugin code.

`<plugin name="cordova-plugin-firebase-dynamiclinks">`
	     `<param name="APP_DOMAIN" value="test.com"/>`
	     `<param name="PAGE_LINK_DOMAIN" value="test.page.link"/>`
	     `<param name="FIREBASE_DYNAMIC_LINKS_VERSION" value="16.0.0"/>`
`</plugin>`

`<preference name="phonegap-version" value="cli-8.0.0"/>`

I got the build but dynamic links plugin not installed. It doesn't exists if i extract the APK and check the plugin folder. Any idea?

**Comment by NrujalSharma** [comment]
Yes even I am facing the same problem, any solutions?

**Comment by NrujalSharma** [comment]
I have already put the code in platform.ready() but it still doesn't work.
Any idea on how to solve this?

**Comment by NrujalSharma** [comment]
I even extracted the apk and checked the plugins folder, the plugin is not present in the apk.

**Comment by NrujalSharma** [comment]
I got the solution.
Your project's cordova version should be 9.0.0 and above and cordova android should be 8.0.0 and above.
Change their versions to the respective version like: 
    "cordova": "^9.0.0",
    "cordova-android": "^8.0.0"
And then run
    npm update

**Comment by rajashekaranugu** [comment]
cannot install this plugin for iOS

ERROR
[!] CocoaPods could not find compatible versions for pod "FirebaseAnalytics":
  In snapshot (Podfile.lock):
    FirebaseAnalytics (= 4.2.0, ~> 4.0)

  In Podfile:
    Firebase/Core (~> 6.3.0) was resolved to 6.3.0, which depends on
      FirebaseAnalytics (= 6.0.2)

    FirebaseMessaging (~> 2.0.0) was resolved to 2.0.8, which depends on
      FirebaseAnalytics (~> 4.0)

Specs satisfying the `FirebaseAnalytics (= 4.2.0, ~> 4.0), FirebaseAnalytics (~> 4.0), FirebaseAnalytics (= 6.0.2)` dependency were found, but they required a higher minimum deployment target.

**Comment by rajashekaranugu** [comment]
@chemerisuk can you please let us know which versions to be used here
