### ISSUE TITLE
CocoaPods could not find compatible versions for pod "Firebase/Core":

### ISSUE THREAD

**Issue by mathew-n27** [chemerisuk/cordova-plugin-firebase-dynamiclinks#45]
Hi,

I am unable to install this plugin along with another plugin [cordova-plugin-firebase-lib](https://github.com/wizpanda/cordova-plugin-firebase-lib). I am using this in Ionic 4 project with `Cordova 9` and `cordova-ios 5`.

Requirements for this plugin are:
```
<pod name="Firebase/Core" spec="~> 6.3.0" />
<pod name="Firebase/DynamicLinks" spec="~> 6.3.0" />
```

Requirements for other plugin are:
```
<pod name="Firebase/Core" spec="5.20.2"/>
<pod name="Firebase/Auth" spec="5.20.2"/>
<pod name="Firebase/Messaging" spec="5.20.2"/>
<pod name="Firebase/Performance" spec="5.20.2"/>
<pod name="Firebase/RemoteConfig" spec="5.20.2"/>
<pod name="Fabric" spec="1.10.2"/>
<pod name="Crashlytics" spec="3.13.2"/>
```

If I install this plugin alone it installs, if I install this plugin after above mentioned plug in it fails to install with the following error message:
```
[!] CocoaPods could not find compatible versions for pod "Firebase/Core":
  In Podfile:
    Firebase/Core (~> 6.3.0)

None of your spec sources contain a spec satisfying the dependency: `Firebase/Core (~> 6.3.0)`.

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```

I removed "Pod" section from this plugin and it installed, then added it manually to pod file without version and pod installed `FirebaseDynamicLinks (3.4.3)`, if I specify version `6.3.0` previous error is triggered. However, Dynamic Link Interception still not working.

Is there a way to fix this error and install this plugin normally?

Any help will be much appreciated.

**Comment by viewpnt1** [comment]
Try updating your pods - "pod repo update"

**Comment by mathew-n27** [comment]
Thanks for the reply, done that same error.

**Comment by karen1au** [comment]
@mathew-n27 hi did you manage to resolve this? I'm getting this when updating to 6.0.1
