### ISSUE TITLE
iOS app open  but does not fire onDynamicLink 

### ISSUE THREAD

**Issue by premtemp1** [chemerisuk/cordova-plugin-firebase-dynamiclinks#45]
Hello,
 I install the plugin but action is not getting fired...

Here is my JS:

  window.cordova.plugins.firebase.dynamiclinks.onDynamicLink(function(data) {
              alert("Dynamic link click with data: ", data);
     });

There is a close item that said to add

if(!handled){
        [dl sendDynamicLinkData:@{
                                  @"deepLink": userActivity.webpageURL.absoluteURL.absoluteString,
                                  @"matchType": @"None"
                                  }];

I did..but still not getting fired

I also install cordova analytics plugin  and i see the 

2018-03-12 10:12:10.609142-0400 RandJobs[1014:807206] 4.10.1 - [Firebase/Analytics][I-ACS023001] Deep Link does not contain valid required params. URL params: {
    ibi = "com.rand.randjobs";
    isi = 1060698980;
    ius = randjobs;
    link = "https://www.rand.com/hello/world";
}

My app opens but the onDynamicLink is not getting fired...
Thanks

**Comment by chemerisuk** [comment]
Firebase Dynamic Links SDK has [unresolved bug](https://github.com/firebase/firebase-ios-sdk/issues/233) related to parsing `deepLink` for new app installs. It order to get it work your dynamic link MUST have [app preview page](https://firebase.google.com/docs/dynamic-links/link-previews), which is the default setting.

**Comment by kunalkakkad** [comment]
Hello,

I am also facing the same issue.
@chemerisuk How come it is related with app preview page setting as the same deeplink is working for android perfectly. On issue is onDynamicLink function is not called in iOS.

Can you please look at the matter and let me know the possible workarounds for the same?

Thanks,
Kunal Kakkad
