### ISSUE TITLE
Dynamic Links does not recognise first time

### ISSUE THREAD

**Issue by bhavinwebdesk** [chemerisuk/cordova-plugin-firebase-dynamiclinks#46]
Hello Team,

I tried to open app using firebase dynamic but it does open link but not detect links.It is calling sendToJs also. I narrow down problem and found that

`- (void) sendToJs {
  // Send the last event to JS if we have one
  if (_handlers.count == 0 || _lastEvent == nil) {
      NSLog(@"We have no handler so return null");
    return;
  }`

I am initialising Dynamic Links at:

`platform.ready().then(() => {
this.firebaseDynamicLinks.onDynamicLink()
    .then((res: any) => {
      //{"matchType":"Strong","deepLink":"https://app.keyy.io/invite/288APPTESTER0112?utm_medium=288&utm_source=invite"}
      console.log("we got success dynamic link::" + JSON.stringify(res));
}
}).catch(e => {
        console.error('error ouccrred', e);
});
` 

should I wait for Platform.ready?

Information:

ionic (Ionic CLI) : 3.19.1
cordova (Cordova CLI) : 7.1.0
System:
    ios-deploy : 1.9.2
    Node       : v8.8.0
    npm        : 5.5.1
    OS         : macOS Sierra
    Xcode      : Xcode 9.2 Build version 9C40b
Device: iPhone 6 ios 11.2

**Comment by premtemp** [comment]
@bhavinwebdesk 
Were able to fix your issue?. 
In my version , the onDynamicLink is never call but yet my app opens ...

**Comment by chemerisuk** [comment]
> Firebase Dynamic Links SDK has [unresolved bug](https://github.com/firebase/firebase-ios-sdk/issues/233) related to parsing `deepLink` for new app installs. It order to get it work your dynamic link MUST have [app preview page](https://firebase.google.com/docs/dynamic-links/link-previews), which is the default setting.
