### ISSUE TITLE
Andoid build error

### ISSUE THREAD

**Issue by Supriyuadi** [chemerisuk/cordova-plugin-firebase-dynamiclinks#47]
Hi, i always get this error when i build for android.

......../android/app/src/main/java/by/chemerisuk/cordova/firebase/FirebaseDynamicLinksPlugin.java:104: error: cannot find symbol
        builder.setDomainUriPrefix(params.optString("domainUriPrefix", this.domainUriPrefix));
               ^
  symbol:   method setDomainUriPrefix(String)
  location: variable builder of type Builder
1 error

FAILURE: Build failed with an exception.

Thaks before.

**Comment by DanTheMan-NL** [comment]
Same! I can’t use this plugin because my build always fails with the same error. Will there be an update soon? 

I use Android platform 8.1.0 and cordova 9.0.0

**Comment by chemerisuk** [comment]
Always use the latest version.
