### ISSUE TITLE
Installation failed: Error: pod: Command failed with exit code 1

### ISSUE THREAD

**Issue by cmartin81** [chemerisuk/cordova-plugin-firebase-dynamiclinks#5]
I'm trying to install your plugin but i get this error:

    Failed to install 'cordova-plugin-firebase-dynamiclinks': Error: pod: Command failed with exit code 1
      at ChildProcess.whenDone (/Users/..../platforms/ios/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
      at emitTwo (events.js:125:13)
      at ChildProcess.emit (events.js:213:7)
      at maybeClose (internal/child_process.js:927:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

cli packages: (/Users/christianmartin/.nvm/versions/node/v8.4.0/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.5
    Cordova Platforms  : ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.2 
    Node       : v8.4.0
    npm        : 5.2.0 
    OS         : macOS High Sierra
    Xcode      : Xcode 9.3.1 Build version 9E501

**Comment by cmartin81** [comment]
Here are some more info:

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-myproject`: (``)

    Finding Podfile changes
      A Firebase
      - FirebaseMessaging

    Resolving dependencies of `Podfile`
    [!] CocoaPods could not find compatible versions for pod "FirebaseAnalytics":
      In snapshot (Podfile.lock):
        FirebaseAnalytics (= 4.2.0, ~> 4.0)

      In Podfile:
        Firebase/Core (~> 5.0) was resolved to 5.0.1, which depends on
          FirebaseAnalytics (= 5.0.0)

        FirebaseMessaging (~> 2.0.0) was resolved to 2.0.8, which depends on
          FirebaseAnalytics (~> 4.0)

Any ide how I can fix this?

**Comment by chemerisuk** [comment]
```
cd platforms/ios
pod update
cordova build
```

**Comment by cmartin81** [comment]
I did not work. Still the same error.

**Comment by chemerisuk** [comment]
You have an old version of `FirebaseMessaging`. Check plugins for firebase messaging you use

**Comment by cmartin81** [comment]
Yes I'm using phonegap-plugin-push which uses an old FirebaseMessaging version..

**Comment by cmartin81** [comment]
I downgraded the pod versions in you plugin in another fork. Now it is compiling successfully.
