### ISSUE TITLE
Firebase Dynamic Links plugin cannot be installed on iOS

### ISSUE THREAD

**Issue by rajashekaranugu** [chemerisuk/cordova-plugin-firebase-dynamiclinks#52]
Hi There,
I have followed the instructions using "https://ionicframework.com/docs/v3/native/firebase-dynamic-links/" and "https://github.com/chemerisuk/cordova-plugin-firebase-dynamiclinks"

**I have added the below in my config.xml**

    <preference name="GoogleIOSClientId" value="xxx49900----" />

**Then** --Added platform ionic cordova platform add ios@5.0.0

**then** ionic cordova plugin add cordova-plugin-firebase-dynamiclinks --variable APP_DOMAIN="example.com" --variable PAGE_LINK_DOMAIN="example.page.link"

**And got this error**
Installing "cordova-plugin-firebase-dynamiclinks" for ios
Running command: pod install --verbose
Failed to install 'cordova-plugin-firebase-dynamiclinks': Error: pod: Command failed with exit code 1
    at ChildProcess.whenDone (/Users/dev/Ionic4/untitled folder/MMAUIRepo/node_modules/cordova-common/src/superspawn.js:135:23)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
pod: Command failed with exit code 1

**Tried updating pod** 

and ended up with
$ pod update
Update all pods
Updating local specs repositories
  $ /usr/bin/git -C /Users/dev/.cocoapods/repos/master fetch origin --progress
  remote: Enumerating objects: 67, done.        
  remote: Counting objects: 100% (67/67), done.        
  remote: Compressing objects: 100% (45/45), done.        
  remote: Total 45 (delta 30), reused 0 (delta 0), pack-reused 0        
  From https://github.com/CocoaPods/Specs
     61d3b0edeeb..aa4a6a3f478  master     -> origin/master
  $ /usr/bin/git -C /Users/dev/.cocoapods/repos/master rev-parse --abbrev-ref HEAD
  master
  $ /usr/bin/git -C /Users/dev/.cocoapods/repos/master reset --hard origin/master
  HEAD is now at aa4a6a3f478 [Add] Ensighten-no-idfa 2.1.4
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "FirebaseCore":
  In Podfile:
    Firebase/Core (~> 6.3.0) was resolved to 6.3.0, which depends on
      Firebase/CoreOnly (= 6.3.0) was resolved to 6.3.0, which depends on
        FirebaseCore (= 6.0.3)

    Firebase/Core (~> 6.3.0) was resolved to 6.3.0, which depends on
      FirebaseAnalytics (= 6.0.2) was resolved to 6.0.2, which depends on
        FirebaseCore (~> 6.0)

    FirebaseMessaging (~> 2.0.0) was resolved to 2.0.8, which depends on
      FirebaseCore (~> 4.0)

Can some one please help me here, struggling with this issue since couple of days

Thanks
Raj

**Comment by rajashekaranugu** [comment]
FYI 
ionic info

Ionic:

   Ionic CLI                     : 5.4.4 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.8.1
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.1, (and 18 other plugins)

Utility:

   cordova-res : 0.8.0 (update available: 0.8.1)
   native-run  : not installed

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.2
   NodeJS     : v10.16.3 (/usr/local/bin/node)
   npm        : 6.4.1
   OS         : macOS Mojave
   Xcode      : Xcode 11.1 Build version 11A1027


And 

**in pod**
        pod 'FirebaseMessaging',  '~ > 2.0.0'
	pod 'Firebase/Core',  '~ > 6.3.0'
	pod 'Firebase/DynamicLinks',  '~ > 6.3.0'

**Comment by danconte72** [comment]
I've did this workaround so far https://github.com/meumobi/nfmb-web/issues/74#issuecomment-576785331

**Comment by skout90** [comment]
@danconte72 thanks.

change pod file below. problem solved

```
pod 'Firebase/Analytics', '~> 6.13.0'
pod 'Firebase/DynamicLinks', '~> 6.13.0'
```

**Comment by Crypt0Graphic** [comment]
> pod 'Firebase/DynamicLinks', '~> 6.13.0'

Where is that pod file?

**Comment by Crypt0Graphic** [comment]
I have a six month ionic project and i can add cordova-plugin-firebase-dynamiclinks without problem.

When i try on my -2 week- new project, no way. I tried everything that i read. Now i try to sync package.json with old project's. Btw, old project has newer packages.

**Comment by chemerisuk** [comment]
Just use the latest version

**Comment by Crypt0Graphic** [comment]
> Just use the latest version

Latest version didn't work for me. So i still use 6.13.0 solution. :/
