### ISSUE TITLE
did not get response from the createDynamicLink

### ISSUE THREAD

**Issue by Rajdev2011** [chemerisuk/cordova-plugin-firebase-dynamiclinks#56]
did not getting any response from the method createDynamicLink.anything wrong 

installed the plugin with app_domain="promotion.domain.com" and PAGE_LINK_DOMAIN=""*.page.link"

anything iam doing wrong in this.

**Comment by cmohanraj10** [comment]
Same issue for me as well

**Comment by Rajdev2011** [comment]
its working for me 
1.add that in config.xml(app domain and pagelink)
2.removed the platform
3.add again the platform

**Comment by cmohanraj10** [comment]
> its working for me
> 1.add that in config.xml(app domain and pagelink)
> 2.removed the platform
> 3.add again the platform

This is my code : 
`<plugin name="cordova-plugin-firebase-dynamiclinks">`
     `<param name="APP_DOMAIN" value="domain.com"/>`
	`<param name="PAGE_LINK_DOMAIN" value="domain.page.link"/>`
`</plugin>`

I can able to get the build and app also opens when the deep link clicked but its not coming under onDynamicLink function. Anything else missing?

**Comment by Rajdev2011** [comment]
> 
> 
> > its working for me
> > 1.add that in config.xml(app domain and pagelink)
> > 2.removed the platform
> > 3.add again the platform
> 
> This is my code :
> `<plugin name="cordova-plugin-firebase-dynamiclinks">`
> `<param name="APP_DOMAIN" value="domain.com"/>`
> `<param name="PAGE_LINK_DOMAIN" value="domain.page.link"/>`
> `</plugin>`
> 
> I can able to get the build and app also opens when the deep link clicked but its not coming under onDynamicLink function. Anything else missing?

  <plugin name="cordova-plugin-firebase-dynamiclinks" spec="4.0.2">
    <param name="APP_DOMAIN" value="test.domain.com" />
    <param name="PAGE_LINK_DOMAIN" value="xxx" />
    <param name="FIREBASE_DYNAMIC_LINKS_VERSION" value="17.2.+" />
 </plugin>

xxx - its the domain created in firebase 

i have created referral.domain.com

**Comment by cmohanraj10** [comment]
Yes, I have created domain in firebase and we do have firebase logins which works fine as well.

deep links will be domainname.page.link/AGne

**Comment by Rajdev2011** [comment]
ok then 
 
  `  <plugin name="cordova-plugin-firebase-dynamiclinks" spec="4.0.2">
    <param name="APP_DOMAIN" value="domain.com" />
    <param name="PAGE_LINK_DOMAIN" value="domain.link" />
    <param name="FIREBASE_DYNAMIC_LINKS_VERSION" value="17.2.+" />
 </plugin>`

 

APP_DOMAIN = domain.com is the domain which you are passing to dynamic link
PAGE_LINK_DOMAIN = is your firebase link which u can see while creating a new dynamic link

**Comment by cmohanraj10** [comment]
I have tried this also, but it doesn't help.

`<plugin name="cordova-plugin-firebase-dynamiclinks" spec="4.0.2">`
	`<param name="APP_DOMAIN" value="domain.com"/>`
	`<param name="PAGE_LINK_DOMAIN" value="domain.page.link"/>`
	`<param name="FIREBASE_DYNAMIC_LINKS_VERSION" value="17.2.1"/>`
`</plugin>`

**Comment by Senglean** [comment]
any success on this ? i have the same issue

**Comment by chemerisuk** [comment]
Fixed iOS-specific bug in 6.1.1. May be it was your problem.
