### ISSUE TITLE
Could not find compatible version for dependency Firebase/Analytics

### ISSUE THREAD

**Issue by brian-slate** [chemerisuk/cordova-plugin-firebase-dynamiclinks#58]
`ionic cordova plugin add cordova-plugin-firebase-dynamiclinks --variable APP_DOMAIN="xxx.xxx.xxx" --variable PAGE_LINK_DOMAIN="xxx.page.link" --verbose`

Errors out due to:
```
[!] CocoaPods could not find compatible versions for pod "Firebase/Analytics":
  In Podfile:
    Firebase/Analytics (~> 6.3.0)

None of your spec sources contain a spec satisfying the dependency: `Firebase/Analytics (~> 6.3.0)`.
```

If I update my platforms/ios/Podfile to use 6.11.0 like:
```
	pod 'Firebase/Analytics', '6.11.0'
	pod 'Firebase/DynamicLinks', '6.11.0'
```
then everything is hunky dory for `pod install`. Is there a way to specifically override this plugin's plugin.xml podspec versions for these two plugins in my config.xml?

**Comment by brian-slate** [comment]
Note, I've tried `pod repo update` as well - and have hooks for this in my config.xml `<hook src="update_pods.sh" type="before_platform_add" />` so that doesn't seem to be the issue. Somewhere the dependencies do not seem to be resolving, and possibly an incompatibility between this and cordova-plugin-firebasex?

Curious if anyone else has run into this issue, or knows of a way to resolve dependency issues for an ionic/cordova app using cocoapods.

**Comment by danconte72** [comment]
I've did this workaround to work so far
https://github.com/meumobi/nfmb-web/issues/74#issuecomment-576885644

**Comment by chemerisuk** [comment]
@bmherold just use the latest published version.
