### ISSUE TITLE
Addition of cordova-plugin-firebase-dynamiclinks to Ionic 4 project renders unable to build

### ISSUE THREAD

**Issue by timstoute** [chemerisuk/cordova-plugin-firebase-dynamiclinks#59]
Would appreciate any guidance on how to resolve conflict with plugins when building Ionic 4 Cordova app for IOS w xcode.

Below are my working plugins - i.e. project builds successfully with these plugins.

BUT, when trying to add cordova-plugin-firebase-dynamiclinks using:

cordova plugin add cordova-plugin-firebase-dynamiclinks --variable APP_DOMAIN="example.ca" --variable PAGE_LINK_DOMAIN="example.page.link";

addition fails with error:

`Failed to install 'cordova-plugin-firebase-dynamiclinks': Error: pod: Command failed with exit code 31
    at ChildProcess.whenDone (/Users/name/project/node_modules/cordova-common/src/superspawn.js:135:23)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
pod: Command failed with exit code 31`

As discovered through search, I have tried:

platforms/ios/pod repo update platforms/ios/pod install

which execute successfully prior to addition of cordova-plugin-firebase-dynamiclinks

MY WORKING SET OF PLUGINS (these build w/ success prior to addition of dynamiclinks plugin):

cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.1.0 "cordova-plugin-androidx-adapter"
cordova-plugin-datepicker 0.9.3 "DatePicker"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-firebasex 7.0.1 "Google Firebase Plugin"
cordova-plugin-google-analytics 1.8.6 "Google Universal Analytics Plugin"
cordova-plugin-googleplus 8.2.1 "Google SignIn"
cordova-plugin-inappbrowser 3.2.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.1.3 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-sqlite-storage 3.4.1 "Cordova sqlite storage plugin - cordova-sqlite-storage plugin version"
cordova-support-google-services 1.3.2 "cordova-support-google-services" 

MY IONIC INFO:

Ionic CLI : 5.4.15 (/usr/local/lib/node_modules/ionic) Ionic Framework : @ionic/angular 4.11.8 @angular-devkit/build-angular : 0.800.6 @angular-devkit/schematics : 8.1.3 @angular/cli : 8.2.2 @ionic/angular-toolkit : 2.0.0

Cordova:

Cordova CLI : 9.0.0 (cordova-lib@9.0.1) Cordova Platforms : ios 5.1.1 Cordova Plugins : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 14 other plugins)

Utility:

cordova-res : 0.8.1 native-run (update available: 0.3.0) : 0.2.8

System:

ios-sim : 8.0.2 NodeJS : v10.16.3 (/usr/local/bin/node) npm : 6.13.6 OS : macOS Mojave Xcode : Xcode 11.3.1 Build version 11C504

**Comment by NagendraMNK** [comment]
is there any solution for this, I am getting same issue for android and iOS 

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:preDebugBuild'.
> In project 'app' a resolved Google Play services library dependency depends on another at an exact version (e.g. "[17.0.
  4]", but isn't being resolved to that version. Behavior exhibited by the library will be unknown.

  Dependency failing: com.google.firebase:firebase-messaging:17.3.4 -> com.google.firebase:firebase-iid@[17.0.4], but fire
  base-iid version was 20.0.2.

  The following dependencies are project dependencies that are direct or have transitive dependencies that lead to the art
  ifact with the issue.
  -- Project 'app' depends onto com.google.firebase:firebase-messaging@17.3.4
  -- Project 'app' depends onto com.google.firebase:firebase-analytics@17.2.2
  -- Project 'app' depends onto com.google.android.gms:play-services-measurement-api@17.2.2
  -- Project 'app' depends onto com.google.firebase:firebase-config@19.0.3
  -- Project 'app' depends onto com.google.firebase:firebase-analytics@17.2.1
  -- Project 'app' depends onto com.google.android.gms:play-services-tagmanager-api@17.0.0
  -- Project 'app' depends onto com.google.firebase:firebase-iid@20.0.2
  -- Project 'app' depends onto com.google.android.gms:play-services-tagmanager@17.0.0
  -- Project 'app' depends onto com.google.firebase:firebase-perf@19.0.1
  -- Project 'app' depends onto com.google.firebase:firebase-analytics@17.2.+

  For extended debugging info execute Gradle from the command line with ./gradlew --info :app:assembleDebug to see the dep
  endency paths to the artifact. This error message came from the google-services Gradle plugin, report issues at https://
  github.com/google/play-services-plugins and disable by adding "googleServices { disableVersionCheck = false }" to your b
  uild.gradle file.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by NagendraMNK** [comment]
after running below plugin, firebase dependency errors will go off and can build android build you Cordova

ionic cordova plugin add cordova-android-firebase-gradle-release  --variable firebase-core=17.0.0 --variable firebase-messaging=19.0.0

Still this is not good suggestion to add dynamic plugin including one more extra plugin after firebase

**Comment by Crypt0Graphic** [comment]
> after running below plugin, firebase dependency errors will go off and can build android build you Cordova
> 
> ionic cordova plugin add cordova-android-firebase-gradle-release --variable firebase-core=17.0.0 --variable firebase-messaging=19.0.0
> 
> Still this is not good suggestion to add dynamic plugin including one more extra plugin after firebase

Your problem seems like different? I get same error like @timstoute:

`Command finished with error code 31: pod install,--verbose`

Your suggestion didn't work for this error. :/

**Comment by skout90** [comment]
@Crypt0Graphic  if you use firebasex plugin, reference this
https://github.com/chemerisuk/cordova-plugin-firebase-dynamiclinks/issues/60
