### ISSUE TITLE
It does not work with android 4.4.4

### ISSUE THREAD

**Issue by cmartin81** [chemerisuk/cordova-plugin-firebase-dynamiclinks#6]
The plugin does not support android 4.4.4. It gives a white screen on startup. :(
I'm using it with the variable FIREBASE_DYNAMIC_LINKS_VERSION=15.0.2

As long as this code is present (do not have to be executed) android 4.4.4 will failed: 

    window.cordova.plugins.firebase.dynamiclinks.onDynamicLink(function(data) { ....})

**Comment by chemerisuk** [comment]
Do you have logcat logs?

**Comment by cmartin81** [comment]
No I do not have logcat installed hence no logs. Are there anything else I can do? I thought of just offer dynamiclinks to android users who has a newer version than 4.4.4. Problem is that the code cannot be present at all, or it will fail.

When I run it on the device and open up chrome developer tools it gives my the following error:

    Uncaught ReferenceError: webpackJsonp is not defined

**Comment by cmartin81** [comment]
Well it looks like cordova plugins for android version 4.4.4 are very fragile regarding ES6 syntaks. I replaced everything inside my onDynamicLink method with a console.log. And then it worked again!
