### ISSUE TITLE
Conflict with cordova-plugin-firebasex

### ISSUE THREAD

**Issue by Crypt0Graphic** [chemerisuk/cordova-plugin-firebase-dynamiclinks#60]
When i try to install cordova-plugin-firebase-dynamiclinks on an Ionic 4 project, it fails if cordova-plugin-firebasex plugin installed before. Vise versa, if DynamicLinks installed can not install FirebaseX.

`Failed to install 'cordova-plugin-firebasex': Error: pod: Command failed with exit code 31`

Update:

I found a workaround then i tried to update Platform/Ios/Podfile as
```
	pod 'Firebase/Analytics', '~> 6.3.0'
	pod 'Firebase/DynamicLinks', '~> 6.3.0'
```
to 
```
	pod 'Firebase/Analytics', '~> 6.13.0'
	pod 'Firebase/DynamicLinks', '~> 6.13.0'
```

Then everything is ok. I can install FirebaseX and build project. So it's about this package. I guess you should update cordova-plugin-firebase-dynamiclinks/plugin.xml as:

```
<pods>
<pod name="Firebase/Analytics" spec="~> 6.13.0" />
<pod name="Firebase/DynamicLinks" spec="~> 6.13.0" />
</pods>
```

**Comment by Sampath-Lokuge** [comment]
It didn't work for me.

Error:

```
cordova.cmd build android
Generating initial manifest for Ionic Deploy...
Ionic Deploy initial manifest successfully generated.
cordova-plugin-androidx-adapter: Processed 35 Java source files in 3862ms
Cannot find module 'xml2js'
Require stack:
- D:\Clients\Phillip\client\plugins\cordova-plugin-firebasex\scripts\after_prepare.js
- C:\Users\Sampath\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\hooks\HooksRunner.js
- C:\Users\Sampath\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js
- C:\Users\Sampath\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\plugman.js
- C:\Users\Sampath\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\cordova-lib.js
- C:\Users\Sampath\AppData\Roaming\npm\node_modules\cordova\src\help.js
- C:\Users\Sampath\AppData\Roaming\npm\node_modules\cordova\src\cli.js
- C:\Users\Sampath\AppData\Roaming\npm\node_modules\cordova\bin\cordova
```

**Comment by chemerisuk** [comment]
This is an issue in cordova-plugin-firebasex

**Comment by Sampath-Lokuge** [comment]
Hi @chemerisuk 
What did you mean by the FirebaseX issue? It is working perfectly fine without your plugin. This issue only comes when I installed your plugin.

**Comment by skout90** [comment]
@Sampath-Lokuge i solved just now.

cordova firebasex plugin update devendency 6.13.0 => 6.17.0

so you must sync dependency version like this

```
<pods>
   <pod name="Firebase/Analytics" spec="~> 6.17.0" />
   <pod name="Firebase/DynamicLinks" spec="~> 6.17.0" />
</pods>
```

**Comment by Sampath-Lokuge** [comment]
@skout90 It is really painful to do plugin configuration changes since we remove the plugin folder and etc time to time due to varies issues. So we have decided to go with Branchio: https://branch.io/what-is-deep-linking/

**Comment by Crypt0Graphic** [comment]
With new FirebaseX version this solution does not work so easily. So you can use old version of FirebaseX like:

ionic cordova plugin add cordova-plugin-firebasex@7.0.2

But these are really painful solutions.

**Comment by crebuh** [comment]
> @Sampath-Lokuge i solved just now.
> 
> cordova firebasex plugin update devendency 6.13.0 => 6.17.0
> 
> so you must sync dependency version like this
> 
> ```
> <pods>
>    <pod name="Firebase/Analytics" spec="~> 6.17.0" />
>    <pod name="Firebase/DynamicLinks" spec="~> 6.17.0" />
> </pods>
> ```

where did you put this stuff? inside config.xml?

**Comment by skout90** [comment]
@crebuh in my case, fork this dynamic link repo. then edited plugins.xml

**Comment by crebuh** [comment]
@skout90 

thx I added cordova-plugin-cocoapod-support and then at least the build worked. dynamic links still not working correctly on iOS now the links go to the app and even open it, but then the callback is not executed, so I'm not able to redirect the user after that point :/

**Comment by mkwiecienn** [comment]
@crebuh I have the same issue - did  you resolve it?
