### ISSUE TITLE
pod spec needs to be updated to newer version in order to remove UIWebView references

### ISSUE THREAD

**Issue by jacobg** [chemerisuk/cordova-plugin-firebase-dynamiclinks#62]
From Apple:
> TMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs starting from December 2020 . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

Currently this plugin depends on an old version of Firebase iOS: 6.3.0. It's from June 2019.  In August, Firebase removed UIWebView from DynamicLinks:
https://github.com/firebase/firebase-ios-sdk/pull/3723/files

This plugin should update to a new version of Firebase iOS so that it's compliant with Apple's deprecation of UIWebView.

**Comment by chemerisuk** [comment]
@jacobg 
> Currently this plugin depends on an old version of Firebase iOS: 6.3.0

This is no fully correct. I specified only the minimum pod version. You can always upgrade to the latest with `pod update`.

**Comment by jacobg** [comment]
Does `cordova` run `pod update` in the build, or are you saying to add a build hook with a script to do that?

**Comment by chemerisuk** [comment]
Run the command manually if you need to update pods to the latest versions.

**Comment by jacobg** [comment]
You had opened a `cordova-ios` issue to support variables for `podspec`:
https://github.com/apache/cordova-ios/issues/721

Though that issue was resolved with a merged pull request, that feature is not yet in a published version of `cordova-ios` on npm yet. It sounds like you are planning to add configurable variables to this project once the next version of `cordova-ios` is released?

**Comment by chemerisuk** [comment]
@jacobg yes, it's planned.

**Comment by chemerisuk** [comment]
@jacobg latest version updates pod dependency to 6.19.0
