### ISSUE TITLE
iOS - correct lastDynamicLinkData get lost during execution

### ISSUE THREAD

**Issue by luboslav** [chemerisuk/cordova-plugin-firebase-dynamiclinks#65]
The `onDynamicLink` callback returns empty data when app is opened via deeplink (installed app / not in background).

I debugged my application and i observed that `postDynamicLink` function get correct data (absoluteUrl, minimuAppVersion, weakConfidence) and set them to `self.lastDynamicLinkData` because `dynamicLinkCallbackId` is not yet present. But when the data are being read in `onDynamicLink` function they are changed (empty). 

I also observed that postDynamicLink function is executed more than once. 

I am not iOS developer so i could not provide you better information.

**Comment by tzappia** [comment]
I noticed what I think is the same behaviour.

1. iOS app is not running in background, but is installed.
2. Click Dynamic Link.
3. App opens.
4. onDynamicLink callback is fired, but data.deepLink is an empty string.

If I start at step 1 with the app already running in the background, data.deepLink is set to the correct link value.

**Comment by tzappia** [comment]
In my case, it was a conflict caused by [cordova-plugin-firebasex](https://github.com/dpa99c/cordova-plugin-firebasex) (which is a fork of cordova-plugin-firebase.) This pull request for cordova-plugin-firebasex solves the issue. [https://github.com/dpa99c/cordova-plugin-firebasex/pull/419](https://github.com/dpa99c/cordova-plugin-firebasex/pull/419)

**Comment by luboslav** [comment]
I also use cordova-plugin-firebasex in my application. Does every case (app in background / not running in background - android & ios ) work for you now with that merged pull request?

**Comment by luboslav** [comment]
Thanks in advance @tzappia for information.

**Comment by tzappia** [comment]
@luboslav yes, all work as expected now.

**Comment by luboslav** [comment]
@tzappia i am testing dev branch with merged pull request but i still get empty deeplink when app is not running (cold start) ... I am using custom domain, not page.link. I also set FirebaseDynamicLinksCustomDomains in config file, but it didn't help. Do you have any ideas what else could be wrong?

**Comment by tzappia** [comment]
@luboslav I have not yet tried the dev branch, only the fork I mentioned. I'm also using a custom domain. Since I use several domains and only a single one is supported for iOS, I'm just writing the associated-domains in config.xml

```
        <config-file parent="com.apple.developer.associated-domains" target="*/Entitlements-Release.plist">
            <array>
                <string>applinks:domain1</string>
                <string>applinks:domain2</string>
                <string>applinks:domain3</string>
            </array>
        </config-file>
        <config-file parent="com.apple.developer.associated-domains" target="*/Entitlements-Debug.plist">
            <array>
                <string>applinks:domain1</string>
                <string>applinks:domain2</string>
                <string>applinks:domain3</string>
            </array>
        </config-file>
```

**Comment by luboslav** [comment]
I am using that fork, but the pull request you mentioned is not yet merged to master.

**Comment by tzappia** [comment]
@luboslav I'm now seeing the same thing, it no longer works on cold start with the latest version of the fork. I will test with earlier versions of the fork and let you know if I can find the version that was working properly for me.

**Comment by tzappia** [comment]
@luboslav late with a response, but this works for us now that the `getDynamicLink` function exists:
```
document.addEventListener('deviceready', () => {
  cordova.plugins.firebase.dynamiclinks.getDynamicLink().then(data => openLink(data));
  cordova.plugins.firebase.dynamiclinks.onDynamicLink(data => openLink(data));
}, {
  once: true,
  capture: false
});
```

Where `openLink()` is how we route the user to the appropriate place.

**Comment by luboslav** [comment]
Thanks for the update @tzappia.
