### ISSUE TITLE
ionic 4 : Property 'firebase' does not exist on type 'CordovaPlugins'.

### ISSUE THREAD

**Issue by manenisha** [chemerisuk/cordova-plugin-firebase-dynamiclinks#68]
I have installed this plugin in my project successfully. Now I want to create dynamic link and if I am trying to call cordova.plugins.firebase.dynamiclinks.createDynamicLink() method but got error :
**Property 'firebase' does not exist on type 'CordovaPlugins'.**

How to resolve this issue..? How to use cordova.plugings ..?? 
My plugin list

**Comment by chemerisuk** [comment]
@manenisha  Better to ask ionic team.
