### ISSUE TITLE
onDynamicLink not triggered after install

### ISSUE THREAD

**Issue by Sroose** [chemerisuk/cordova-plugin-firebase-dynamiclinks#69]
The plugin seems to record deeplinks just fine whenever the app is already installed. However, when the deeplink opens up the app store (or testflight in my case) and the app needs to be installed first, it does NOT trigger onDynamicLink when the app starts.

Strange enough, when I spoof the traffic, I can see a call being made to https://firebasedynamiclinks.googleapis.com/v1/installAttribution, which returns something like:
`{
  "deepLink": "https://myfinaldeeplink",
  "requestedLink": "https://mycustomdomain/?link=deeplink+params",
  "attributionConfidence": "UNIQUE",
  "matchMessage": "Link is uniquely matched for this device.",
  "requestIpVersion": "IP_V4"
}
`
which proofs that Firebase is in fact picking up and attributing the deeplink correctly. What could be the reason that onDynamicLink is not triggered?

**Test setup:**
- using iOS
- I have onDynamicLink inside this.platform.ready(),
- version of the plugin: "cordova-plugin-firebase-dynamiclinks": "^4.3.0"
- used pods:
pod name="Firebase/Analytics" version="6.21.0"
pod name="Firebase/DynamicLinks" version="6.21.0"

**Comment by Sroose** [comment]
Closing, not because solved but because we moved to Branch.

**Comment by numerized** [comment]
Hello here

How do you get it to open testflight ?

**Comment by newmesiss** [comment]
I have the same problem, it always returns null after installing the application

**Comment by chemerisuk** [comment]
https://github.com/chemerisuk/cordova-plugin-firebase-dynamiclinks/issues/85#issuecomment-735792591

**Comment by newmesiss** [comment]
@chemerisuk yes, I am using getDynamicLink but it still throws me null when the application is not installed and goes through appStore

**Comment by numerized** [comment]
same, I am using 4.7.0 as it is the last working version to me to date

**Comment by Ezio17** [comment]
@numerized @newmesiss Did you solve this problem?
