### ISSUE TITLE
What is the "*.page.link" domain ? 

### ISSUE THREAD

**Issue by ahmadehab** [chemerisuk/cordova-plugin-firebase-dynamiclinks#7]
What is the value of *.page.link that should I add when running the Cordova command line?

**Comment by yushinarch** [comment]
this can be found and created in the firebase console under "Grow (on the side panel)" you will find dynamic links in ther you will be prompted to create a domain and the ending of the domain will be .page.link. i guess thats the link or domain you will need to include.

**Comment by ahmadehab** [comment]
Thank you.
