### ISSUE TITLE
How to add custom Query-Parameters and receive them inside the App?

### ISSUE THREAD

**Issue by NLueg** [chemerisuk/cordova-plugin-firebase-dynamiclinks#74]
Hi there, I currently struggle with passing additional information to the dynamic link from firebase.
I tried several techniques like just adding it to the route like this:

```
https://my.custom.link/share?user=1234
```

I get routed to the App and the method of this plugin gets triggered but I can't receive the additional parameters.
Do I miss something or is this currently not possible at all?

Thank you for your answer.

**Comment by NLueg** [comment]
I finally made it. My mistake was to fill in `domainUriPrefix` and `link` on creating the link. Then I always received the root link.
Now I only fill in the `link` and it works 🎉

**Comment by nuno** [comment]
@NLueg Do you mind to share your example, I have the same issue. Thanks.

**Comment by NLueg** [comment]
@nuno I done it this way:

```ts
      const paramString = `${userParam}&${pantryParam}&${roleParam}&${permissionParam}&${timestampParam}`;

      return this.firebaseDynamicLinks
        .createShortDynamicLink({
          link: `https://my.custom.link/sharing?${paramString}`,
          androidInfo: {
            androidPackageName: "com.mypackage.app",
            androidFallbackLink: "https://my.custom.link/sharing",
          },
          iosInfo: {
            iosFallbackLink: "https://my.custom.link/sharing",
            iosBundleId: "com.mypackage.app",
            iosAppStoreId: "1531156645",
            iosIpadBundleId: "com.mypackage.app",
            iosIpadFallbackLink: "https://my.custom.link/sharing",
          },
        })
```

I hope it helps!
