### ISSUE TITLE
Dynamic Link Listener not triggered on Ios app using capacitor 

### ISSUE THREAD

**Issue by sSarahlei** [chemerisuk/cordova-plugin-firebase-dynamiclinks#77]
Everything works well with android , but on ios the OnDynamicLink function is not triggered when app is entered via a dynamic link.

Digging into the code I saw the the functions under the plugin's AppDelegate file (ex:FirebaseDynamicLinks+AppDelegate.swift) are not called, rather the main AppDelegate.swift functions , specifically the following functions:
" application:continue userActivity:restorationHandler" and "application: UIApplication, open url: URL") are called instead.

After some research I realized that the reason why the method swizzling isn't working, is since the plugin code is in objective-c and the App is is in swift, so when trying to swizzle the App Delegate functions, the function declarations to swizzle don't match.

How to deal with such cases?
I have tried adding the @objc attribute to the App Delegate functions that should be swizzled , with no success .

**Comment by eli-neumann** [comment]
I am having a similar issue when using capacitor

**Comment by chemerisuk** [comment]
Ask capacitor team, this is a cordova plugin.
