### ISSUE TITLE
Doesn't fire methods during cold launch in iOS

### ISSUE THREAD

**Issue by anthropoy** [chemerisuk/cordova-plugin-firebase-dynamiclinks#8]
Hi Chemerisuk, I realised that in iOS, it doesn't fire any of the methods when it cold-launched from a deeplink. It works perfectly when it becomes active from background. After some digging in your code, I realised that it did not have the method didFinishLaunchingWithOptions. So I have tried adding in a listener in pluginInitialize method for this didFinishLaunchingWithOptions method but strangely it only calls this method once at the very first time when I built the code for debug in xcode, when I tried to debug again with a cold launch, it doesn't call this again. Any ideas? Thanks.

**Comment by chemerisuk** [comment]
Dynamic links are tricky to test. I recommend to look at https://m.youtube.com/watch?v=sFPo296OQqk and make sure you are invoking the same steps

**Comment by anthropoy** [comment]
Ok, thanks, I'll check out the video but what are your thoughts about firing up the links during cold launch in iOS? And my comments about the didFinishLaunchingWithOptions, is that the right way to make sure it will be called during cold launch or there are other methods that you think is better?

**Comment by chemerisuk** [comment]
@anthropoy callback fired on iOS during cold launch on my side. Make sure you are doing all steps correctly.

**Comment by chemerisuk** [comment]
Try 0.10.0
