### ISSUE TITLE
Can't find FirebaseDynamicLinksPlugin after capacitor build

### ISSUE THREAD

**Issue by karen1au** [chemerisuk/cordova-plugin-firebase-dynamiclinks#80]
Hi, I'm using vue on capacitor, and got the error below when running the app in Android studio
```
2020-09-29 16:25:55.570 6627-6734/? W/System.err: java.lang.ClassNotFoundException: by.chemerisuk.cordova.firebase.FirebaseDynamicLinksPlugin
2020-09-29 16:25:55.571 6627-6734/? W/System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "by.chemerisuk.cordova.firebase.FirebaseDynamicLinksPlugin" on path...
```
When I look for the actual plugin file, I only see the FirebaseAuthenticationPlugin in the folder, weirdly even when I uninstall that plugin, that file still exists.
![image](https://user-images.githubusercontent.com/43124859/94614684-91c4fc80-0274-11eb-9485-44e37af36e81.png)

In the terminal it seems Capacitor is correctly identifying the plugin:
![image](https://user-images.githubusercontent.com/43124859/94615295-858d6f00-0275-11eb-8f0f-6639301138cf.png)

My related dependecies:
```
    "@capacitor/android": "2.4.0",
    "@capacitor/cli": "^2.4.0",
    "@capacitor/core": "^2.4.0",
    "@ionic-native/core": "^5.28.0",
    "@ionic-native/firebase-dynamic-links": "^5.28.0",
    "@ionic/cli": "^6.11.1",
    "cordova-plugin-firebase-dynamiclinks": "^4.6.0",
    "cordova-plugin-ionic": "^5.4.7",
    "cordova-plugin-whitelist": "^1.3.4",
    "cordova-support-android-plugin": "^1.0.2"
```
Am I missing something??

**Comment by chemerisuk** [comment]
@karen1au this is a cordova plugin, ask capacitor team.
