### ISSUE TITLE
 onDynamicLink not detecting when app closed

### ISSUE THREAD

**Issue by shubhamReap** [chemerisuk/cordova-plugin-firebase-dynamiclinks#85]
app not detecting dynamic link click when app is closed, but it is working when app is in background. 

in app.component

`  initializeApp() {
    this.platform.ready().then(() => {
      this.firebaseDynamicLinks.onDynamicLink().subscribe(
        (res: any) => {
          if (res) {
            console.log("firebaseDynamicLinks", res);
          }
        },
        (error: any) => {
          console.log("firebaseDynamicLinks", error);
        }
      );
});
}`

in config

`    <preference name="GoogleAndroidClientId" value="" />
    <preference name="GoogleIOSClientId" value="" />
    <preference name="AndroidLaunchMode" value="singleTask" />`

**how to detect when user click on dynamic link and app is closed
 ?**

**Comment by ahmadklsany** [comment]
downgrade dynamic-link plugin version to 4.4.0 it work for me

**Comment by chemerisuk** [comment]
@shubhamReap @ahmadklsany use new method `getDynamicLink` for getting dynamic link info on app start. `onDynamicLink` callback is triggered only on subsequent calls.

**Comment by chemerisuk** [comment]
More info and motivation of such changes here: https://github.com/chemerisuk/cordova-plugin-firebase-dynamiclinks/issues/54
