### ISSUE TITLE
iOS app crashes on load

### ISSUE THREAD

**Issue by felixphase** [chemerisuk/cordova-plugin-firebase-dynamiclinks#86]
Hello,

I have installed this plugin and it works perfectly for Android. But When I install it is crashing my app on load.
FYI, I am using this plugin to create Dynamic Link from my app.

Error:
<img width="580" alt="Screenshot 2020-10-23 at 11 16 36 AM" src="https://user-images.githubusercontent.com/70378471/96961477-5e4b5a00-1522-11eb-8ad5-8201ba50e484.png">

Although I have kept the correct info.plist file which is generated by Firebase Console.

Ionic Info:
<img width="621" alt="Screenshot 2020-10-23 at 11 25 53 AM" src="https://user-images.githubusercontent.com/70378471/96961554-8cc93500-1522-11eb-9480-9a1d42554885.png">

Plugins list:
<img width="615" alt="Screenshot 2020-10-23 at 11 26 40 AM" src="https://user-images.githubusercontent.com/70378471/96961595-a4082280-1522-11eb-8928-4838acb2d7a4.png">

Kindly let me know this issue resolution as it is not allowing me to move ahead and its very URGENT

**Comment by felixphase** [comment]
Hello,
Without any reason why the issue has been closed?

**Comment by manveloff** [comment]
I've faced the same problem. Only after I opened xCode and manually added "GoogleService-Info.plist" to Resources, it worked.
![image](https://user-images.githubusercontent.com/30803862/138271206-22de663c-d5e1-4ad7-91aa-1471bcccfe92.png)

I suspect the plugin must copy the "GoogleService-Info.plist" from root of a project to the right place, but it doesn't happen for some reason.
