### ISSUE TITLE
Property 'getDynamicLink' does not exist on type

### ISSUE THREAD

**Issue by rahuldmk** [chemerisuk/cordova-plugin-firebase-dynamiclinks#87]
Property '**getDynamicLink**' does not exist on type 'FirebaseDynamicLinks'. Did you mean 'onDynamicLink'?ts(2551)
index.d.ts(89, 5): 'onDynamicLink' is declared here

**Comment by ericgopak** [comment]
Indeed, that's because you're using `@ionic-native` Typescript wrapper.

You can use the Cordova plugin directly, e.g. like this
````
window.cordova.plugins.firebase.dynamiclinks.getDynamicLink()
````
or wait until this pull request is merged: https://github.com/ionic-team/ionic-native/pull/3567

**Comment by ericgopak** [comment]
*Update*: the pull request at `ionic-native` has been merged into master.

**Comment by rahuldmk** [comment]
> _Update_: the pull request at `ionic-native` has been merged into master.

Thank You
