### ISSUE TITLE
4.8.0 is a breaking change, should be versioned : 5.0.0

### ISSUE THREAD

**Issue by numerized** [chemerisuk/cordova-plugin-firebase-dynamiclinks#88]
Hello, since you modified the variable names 4.8.0 should be named 5.0.0 isn't it ?

**Comment by chemerisuk** [comment]
@numerized I was thinking the same... But it should not break anything - you have to specify new variable names during an upgrade to the latest version.

**Comment by numerized** [comment]
yes, it is a breaking change, it has to bump to 5.0.0 I think
