### ISSUE TITLE
iOS getDynamic link return null after app store install

### ISSUE THREAD

**Issue by awkoy** [chemerisuk/cordova-plugin-firebase-dynamiclinks#89]
Hi!
I've a problem with catching a dynamic link data after install app. 

1. Uninstall app
2. Open link and go to app store
3. Install app from XCode or Testflight
4. Opened app init getDynamicLink and it return null

Could you help me, what things can broke this process?
I've tried a lot of ways ( checked all firebase settings for iOS, reinstalled plugins, updated coca ) but it doesn't work(

**Comment by awkoy** [comment]
I've found that "cordova-plugin-facebook4" broke onDynamicLink after install, could you check why?

**Comment by awkoy** [comment]
I've resolve this issue, in FacebookConnectPlugin.m need delete AppDelegate @Override methods, I hope it will be usefull for somebody =)

**Comment by numerized** [comment]
Hello there, 

This still happens.

**Comment by newmesiss** [comment]
I have the same problem
