### ISSUE TITLE
The default Firebase app has not yet been configured.

### ISSUE THREAD

**Issue by jlsuarezs** [chemerisuk/cordova-plugin-firebase-dynamiclinks#9]
Hi,

I am having an issue using the plugin:
[Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add [FIRApp configure] to your application initialization. Read more: https://goo.gl/ctyzm8.

A reversed client ID should be added as a URL scheme to enable Google sign-in.
2017-03-20 11:18:07.202585 MyApp[4072:252847] *** Terminating app due to uncaught exception 'com.firebase.appinvite', reason: 'Firebase Invites has stopped your project due to a misconfiguration in your project that may prevent your app from behaving as expected:

Error: URL scheme needed for Google Sign-In not included in your app's Info.plist. Please refer to the Google Sign-In SDK documentation for more information.'
*** First throw call stack:
(0x1844d91b8 0x182f1055c 0x1844d9100 0x1001994e8 0x100198f8c 0x184472b10 0x184472214 0x184471f90 0x1844e1b8c 0x1843b3e64 0x184ee8e0c 0x10016cf94 0x10016bd3c 0x10016ba34 0x10009b01c 0x10021e800 0x10021ec34 0x10021c594 0x1000486e0 0x18a38e924 0x18a38e4ec 0x18a394c98 0x18a392138 0x18a40468c 0x1002204c0 0x1000483fc 0x18a4006a4 0x18a610a98 0x18a616808 0x18a62b104 0x18a6137ec 0x1860af92c 0x1860af798 0x1860afb40 0x184486b5c 0x1844864a4 0x1844840a4 0x1843b22b8 0x18a3f97b0 0x18a3f4534 0x1000482ec 0x1833955b8)
libc++abi.dylib: terminating with uncaught exception of type NSException

Any idea? :(

Thanks for your help and amazing plugin!
:D

**Comment by jlsuarezs** [comment]
Ok, I've solved this issue following these steps to add a URL scheme to my project:
Add a URL scheme to your project > https://developers.google.com/identity/sign-in/ios/start-integrating

**Comment by chemerisuk** [comment]
Try 0.10.0
