### ISSUE TITLE
I don't get lego link to download from app store

### ISSUE THREAD

**Issue by newmesiss** [chemerisuk/cordova-plugin-firebase-dynamiclinks#91]
When the application is not installed, I go through the browser and it takes me to the app store, I download the app and then start it, and getDynamicLink returns null. Flow only happens when app is not installed

**Comment by tzappia** [comment]
@newmesiss  we are able to get the link from a cold startup using the following flow:
```
document.addEventListener('deviceready', () => {
  cordova.plugins.firebase.dynamiclinks.getDynamicLink().then(data => openLink(data));
  cordova.plugins.firebase.dynamiclinks.onDynamicLink(data => openLink(data));
}, {
  once: true,
  capture: false
});
```

Where `openLink()` is how we route the user to the appropriate place.
