### ISSUE TITLE
Cannot read property 'createShortDynamicLink' of undefined

### ISSUE THREAD

**Issue by arham-anees** [chemerisuk/cordova-plugin-firebase-dynamiclinks#92]
I am using Sentry to track errors, I am getting this error from users they have android 10 and android 9 while we use android 10 for testing purposes. it works perfectly fine here but getting this error from end users.
All these errors are from android OS.
Has anybody else faced it before?
Here is my stats from 191 events from 7 users
![image](https://user-images.githubusercontent.com/29898712/107480504-81b41680-6b9e-11eb-9c9f-9f88b6153ad3.png)

**Comment by AlibekJ** [comment]
Are you sure you are calling the plugin after ```deviceready``` event?

**Comment by arham-anees** [comment]
Yes i am sure i am using this after deviceready
However, it is too late now. We have switched from sentry.
