### ISSUE TITLE
Dynamic link not recognized when app is being launched - again but this time in android 

### ISSUE THREAD

**Issue by sunil9991** [chemerisuk/cordova-plugin-firebase-dynamiclinks#93]
As i have read the same issue but the patch is avaial for ios what about the ANDROID as it is not giving response of deeplink when the app is load at very first time or close from background and reopen in all senerio we arn't getting the deeplink data

**Comment by sunil9991** [comment]
firebase.dynamiclinks.getDynamicLink().then(function(data) {
})

this function works for me for app load

**Comment by nimishdesai1989** [comment]
Hi all

i am still facing this issue with Android on first time when the app is installed from store. Any suggestions on how to solve this ?
