### ISSUE TITLE
getDynamicLink method returns null on launch or open with dynamic link

### ISSUE THREAD

**Issue by churples** [chemerisuk/cordova-plugin-firebase-dynamiclinks#98]
Hi All,

I am having issues getting this plugin to work properly.  On launch (fresh install or not), the app is not returning anything for the getDynamicLink method when a firebase dynamic link is used. 

If there is any other info needed, please let me know.

Plugins I am currently using:
- cordova-plugin-device 2.0.3 "Device"
- cordova-plugin-fcm-ng 8.3.0 "FCMPluginNG"
- cordova-plugin-firebase-analytics 6.0.1 "FirebaseAnalyticsPlugin"
- cordova-plugin-firebase-dynamiclinks 6.0.0 "FirebaseDynamicLinksPlugin"
- cordova-plugin-hostedwebapp 0.3.2 "HostedWebApp"
- cordova-plugin-network-information 2.0.2 "Network Information"
- cordova-plugin-whitelist 1.3.4 "Whitelist"

**Comment by churples** [comment]
Updating this as I have updated the plugin in my project to no avail. Can anyone offer any help on this?
Thanks!!

**Comment by tkou15** [comment]
I had the same problem. But I solved it with the following method.
It seems that I need to call the onDynamicLink method before calling getDynamicLink.


My usage.
```

```

**Comment by tuyenhoangvan** [comment]
> Updating this as I have updated the plugin in my project to no avail. Can anyone offer any help on this? Thanks!!

Hi @churples, I faced with this issue today. When I click dynamic link -> redirect to App Store -> install app -> open app => dynamic link is not working. Then I fixed it by set `enableForcedRedirect = false` when create dynamic link. Pls make sure that you are not ignore links preview when create new dynamic link.
Hope this help!

**Comment by nimishdesai1989** [comment]
I am having the same issue also on Android. The event is not triggered on first launch after the app is installed from store. If the app is already installed and the dynamic link is clicked, then the app works fone with the event being triggered as expected.

any suggestions to solve this issue ?

**Comment by manveloff** [comment]
Maybe try to invoke the getDynamicLink method inside
platform.ready().then(() => {}

**Comment by tzappia** [comment]
Expanding on @manveloff 's suggestion, here's the flow that works for us:
```
document.addEventListener('deviceready', () => {
  cordova.plugins.firebase.dynamiclinks.getDynamicLink().then(data => openLink(data));
  cordova.plugins.firebase.dynamiclinks.onDynamicLink(data => openLink(data));
}, {
  once: true,
  capture: false
});
```

Where `openLink()` is how we route the user to the appropriate place.
