### ISSUE TITLE
"GoogleService-Info.plist" not found

### ISSUE THREAD

**Issue by manveloff** [chemerisuk/cordova-plugin-firebase-dynamiclinks#99]
I've faced the same issue, as described in:
https://github.com/chemerisuk/cordova-plugin-firebase-dynamiclinks/issues/86

The app on iOS crashes on start because the plugin can't find a valid "GoogleService-Info.plist".
Meanwhile, I have the file in my Ionic 5 project's root folder (alongside config.xml).

Only after I opened xCode and manually added "GoogleService-Info.plist" to Resources, it worked.
![image](https://user-images.githubusercontent.com/30803862/138271964-9c6aa8b0-5663-454d-82d8-f0e3f704f362.png)

I suspect the plugin must copy the "GoogleService-Info.plist" from root of a project to the right place, but it doesn't happen for some reason.

**Comment by askona** [comment]
@chemerisuk please update plugin.xml to use latest 6.1.0 analytics plugin

**Comment by chemerisuk** [comment]
I've added a new section with details where config files should be located - https://github.com/chemerisuk/cordova-plugin-firebase-dynamiclinks#adding-required-configuration-files

If you use latest Ionic you have to copy files manually because Capacitor doesn't support Cordova hooks.
